app/build.gradle.kts

Currently, SonarCloud has set the default app name to be `app`. This is because, you need to set the name deliberately as a property.
To fix this we just need to tell SonarCloud what we want the name to be.

Add Sonar projectName property

---

.github/workflows/lint.yml
.github/workflows/sonar_scanner.yml
.github/workflows/unit_test.yml

It can be a potential vulnerability to lock GitHub actions to versions such as @V1
Each action should be locked to the specific commit, rather than version number
- [GOVAPP-461](https://govukverify.atlassian.net/browse/GOVAPP-461)
[GOVAPP-461]: https://govukverify.atlassian.net/browse/GOVAPP-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix GitHub action versions to specific commit

---

app/build.gradle.kts
app/src/main/java/uk/govuk/app/MainActivity.kt
settings.gradle.kts

Pulls in the app modules from [JitPack](jitpack.io). Currently, using the latest `SNAPSHOT` from the `develop` branch. 
- [GOVAPP-455](https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405?selectedIssue=GOVAPP-455)
|---|---|
| ![Screenshot_20240513_152459](https://github.com/alphagov/govuk-mobile-android-app/assets/44037625/9253d421-c4d0-4788-a119-40724be53a8c) | ![Screenshot_20240513_152406](https://github.com/alphagov/govuk-mobile-android-app/assets/44037625/4af3d770-d386-4042-8c05-51aa9a5cd96d) |
[GOVAPP-455]: https://govukverify.atlassian.net/browse/GOVAPP-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add app modules from develop branch via JitPack

---

app/src/main/AndroidManifest.xml
feature/home/src/main/java/uk/govuk/app/home/ui/navigation/HomeNavigation.kt
feature/settings/src/main/java/uk/govuk/app/settings/ui/navigation/SettingsNavigation.kt

Add deep links to top level destinations and a feature sub screen and check that the navigation and back stack behave as expected.
We need to test the built in deep link behaviour of the nav controller is suitable for our use case.
Example use cases:
The ability to send data from a web URL deeplink has been proved [here](https://github.com/gclssvglx/deeplink-test) - see video below. This accounts for the IDV and Wallet journeys.
Data (single element, multiple elements, or serialised objects) can be sent by adding it in the `NavHost` routes, like this...
```kotlin
composable("about",
deepLinks = listOf( /* create deeplink */ ),
arguments = listOf(
navArgument("id") {
type = NavType.IntType
defaultValue = -1
}
)
) { entry ->
AboutScreen(navController, entry.arguments?.getInt("id")) // dig …
```

Add deeplinks for checking/validation

---

app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt

Missing horizontal alignment.
|---|---|
| ![before-portrait](https://github.com/user-attachments/assets/a18a6239-3af3-4389-b912-417ca6d56576) | ![after-portrait](https://github.com/user-attachments/assets/37c925ff-13fb-4427-8d2a-f787fe464874) |
| ![before-landscape](https://github.com/user-attachments/assets/0e112b2c-7934-462f-9b74-f50de960fcc6) | ![after-landscape](https://github.com/user-attachments/assets/ddad910c-968b-4eee-b7f4-ad4e0df6cce9) |
| Difficult to see in portrait |
| --- |
| <img width="1420" alt="Screenshot 2024-07-18 at 13 57 01" src="https://github.com/user-attachments/assets/0d55c765-eb19-4f26-bdce-bfc4fd248962"> |
| Much easier in landscape |
| --- |
| ![Screenshot 2024-07-18 at 14 00 36](https://github.com/user-attachments/assets/8fae1a6d-b85c-466e-b …

Fix alignment issue on splash screen

---

app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt
app/src/test/kotlin/uk/govuk/app/launch/RemoveAnimationsSettingTest.kt

The app is crashing with a RuntimeException.
On investigation, it was discovered that the `ANIMATOR_DURATION_SCALE` [setting](https://developer.android.com/reference/android/provider/Settings.Global#ANIMATOR_DURATION_SCALE) was returning null when attempting to get it via the `getFloat()` [method](https://developer.android.com/reference/android/provider/Settings.Global#getFloat(android.content.ContentResolver,%20java.lang.String)) as recommended, which of course cannot be tested for equality against another Float.
While this setting is stored as a String, it is actually a Float under-the-covers, with a value of 0.0f or 1.0f. In theory, `getFloat()` should be fine with these values. But clearly isn't under some circumstances! Precisely what those circumstances are is unclear. 
We therefore …

Bug fix - animations setting causing the app to crash

---

design/build.gradle.kts
design/src/androidTest/kotlin/uk/govuk/app/design/ui/components/ButtonsTest.kt
design/src/main/kotlin/uk/govuk/app/design/ui/components/Buttons.kt
design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt
design/src/main/res/drawable/baseline_open_in_new_24.xml
feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt
gradle/libs.versions.toml

Update existing Android button component to use [font](https://govukverify.atlassian.net/browse/GOVUKAPP-553), [colour palette](https://govukverify.atlassian.net/browse/GOVUKAPP-554) and [token (https://govukverify.atlassian.net/browse/GOVUKAPP-555) libraries.
- Primary & secondary button
- Highlighted, focussed and disabled states
- [GOVAPP-557](https://govukverify.atlassian.net/browse/GOVUKAPP-557)
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-Apps-and-notifications?node-id=11357-18544&t=Ku5M2JEzz28SBzPr-0)

GOVUKAPP-557 Update Button Component

---

design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt

- [GOVAPP-681](https://govukverify.atlassian.net/browse/GOVUKAPP-681)
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-Apps-and-notifications?node-id=9290-29532&t=osxlMej2WD4DEiOP-0)
|---|---|
| ![Screenshot_20240821_135053](https://github.com/user-attachments/assets/69ba95ae-3a2e-4066-9e30-f1ca2254b97f) | ![Screenshot_20240821_134906](https://github.com/user-attachments/assets/b599aac6-7293-47b0-931a-70f9b441c21f) |
|---|---|
| ![Screenshot_20240821_135146](https://github.com/user-attachments/assets/d705def8-5bc5-4e68-ad85-8bffbadb889f) | ![Screenshot_20240821_135012](https://github.com/user-attachments/assets/b87c471a-92b3-4f17-89fb-4333974e9d33) |

Update trailing icon colour to be in-line with primary text

---

app/src/main/kotlin/uk/govuk/app/ui/SplashScreen.kt

Lottie animations do not support alt text in their JSON file, so for Android we need to add support for this via `Modifler.semantics`.
- [GOVAPP-671](https://govukverify.atlassian.net/browse/GOVUKAPP-671)

GOVUKAPP-671 Add alt text to Splash Screen lottie animation

---

feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt

**What is happening**
When the user is on the onboarding screens and chooses to move from the first screen to the last (or vice versa) - thereby skipping any intermediary screens - Google Analytics (GA) page view events are still fired for those intermediary screens - as if they were viewed. This effectively skews our GA results and we are unable to know that a skip has happened.
For example (given 3 screens)…
- The user is on Screen 1 and wishes to go to Screen 3. GA events for Screen 2 and Screen 3 occur.
- The user is on Screen 3 and wishes to go to Screen 1. GA events for Screen 2 and Screen 1 occur.
- Moving from Screen 1 or Screen 3 to Screen 2 only fires a single GA event form Screen 2 as expected.
**What should happen** 
- The user is on Screen 1 and wishes to go to Screen 3. A …

GOVUKAPP-691 onboarding GA events fired for intermediary screens

---

design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt
design/src/main/kotlin/uk/govuk/app/design/ui/component/Label.kt
design/src/main/kotlin/uk/govuk/app/design/ui/component/Switch.kt
design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt
feature/settings/build.gradle.kts
feature/settings/src/main/kotlin/uk/govuk/app/settings/ui/SettingsScreen.kt
feature/settings/src/main/res/drawable/baseline_open_in_new_24.xml
feature/settings/src/main/res/values/strings.xml

Does the following:
- Creates the Settings page, with title.
- Adds the app version information to the Settings page.
- Adds a switch to the settings page which shows, and can be used to change, the user’s permission on gathering and sending app usage statistics.
- [GOVAPP-673](https://govukverify.atlassian.net/browse/GOVUKAPP-673)
- [GOVUKAPP-675](https://govukverify.atlassian.net/browse/GOVUKAPP-675)
- [GOVUKAPP-677](https://govukverify.atlassian.net/browse/GOVUKAPP-677)
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-Apps-and-notifications?node-id=9290-29532&node-type=CANVAS&t=R8Yq9VtOatjez6vV-0)
- [Switch component designs](https://www.figma.com/design/siD3CH5hRhIAmVTQ10xkjb/GOV.UK-app-library?node-id=0-1&node-type=CANVAS&t=CvNanANcXkEg0Eut-0)
| Light Mode | …

GOVUKAPP 673, 675 & 677 Settings

---

app/build.gradle.kts
app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt
feature/settings/src/main/kotlin/uk/govuk/app/settings/navigation/SettingsNavigation.kt
feature/settings/src/main/kotlin/uk/govuk/app/settings/ui/SettingsScreen.kt
feature/settings/src/main/res/values/strings.xml

Requested changes:
|---|---|
| ![Screenshot_20240906_145246](https://github.com/user-attachments/assets/d69a4b96-49f5-41fc-9f15-7c94ab706fab) | ![Screenshot_20240906_145137](https://github.com/user-attachments/assets/bcf6e550-f297-4b8f-aaf1-fd9211c88c59) |

Settings screen: post amigo changes

---

feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt

`Opens in web browser` was being read by TalkBack twice due to the alt text being on the clickable row and the icon. As we only want it read once and at the end (not the beginning of the readout) - we remove the alt text from the row and leave the alt text on the icon.

Fixes issue with TalkBack reading Opens in web browser twice

---

design/src/main/res/values/strings.xml

When TalkBack is turned on the `X` Clear button incorrectly reads `Clear, Window GOV.UK`. It should read `Clear search`.
The word `search` has been appended to `Clear` to give the correct initial phrase.
However, controlling the second part of what is read, i.e. `Window GOV.UK`, is much more of an issue. On investigation, it seems this is read only on the first time that the user navigates to this screen - all subsequent times the correct phrase `Clear search` is read out. This can be tested by clicking on the back button first `<` then the `X` button. By doing this both back and clear button phrases are correct.
Normally, something like `Window...` is read when the app is first loaded, but not once navigation to a child screen occurs. It is unclear why it is happening here.
I have …

GOVUKAPP-766 - Alt text for clear search button

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml
build.gradle.kts
feature/settings/build.gradle.kts
feature/settings/src/main/kotlin/uk/govuk/app/settings/SettingsViewModel.kt
feature/settings/src/main/kotlin/uk/govuk/app/settings/navigation/SettingsNavigation.kt
feature/settings/src/main/kotlin/uk/govuk/app/settings/ui/SettingsScreen.kt
feature/settings/src/main/res/values/strings.xml
feature/settings/src/test/kotlin/uk/govuk/app/settings/SettingsViewModelTest.kt
gradle/libs.versions.toml

We need a solution to display the app's dependency licences - in-app - with relevant developer information and outward links, which doesn’t require manual population or administration.
Added as per the instructions here:
- https://github.com/google/play-services-plugins/tree/main/oss-licenses-plugin
- https://developers.google.com/android/guides/opensource
- [GOVAPP-679](https://govukverify.atlassian.net/browse/GOVUKAPP-679)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-82977&node-type=canvas&t=bE8WW67KarKR6IY8-0)
| --- | --- |
| ![light-screen-1](https://github.com/user-attachments/assets/84b6ca83-8986-46dc-9ea1-6432a733de4a) | ![dark-screen-1](https://github.com/user-attachments/assets/3606c378 …

GOVUKAPP-679: display open source licences

---

analytics/src/main/kotlin/uk/govuk/app/analytics/Analytics.kt
analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt
analytics/src/test/kotlin/uk/govuk/app/analytics/AnalyticsClientTest.kt
app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt
feature/visited/build.gradle.kts
feature/visited/src/main/kotlin/uk/govuk/app/visited/VisitedViewModel.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/navigation/VisitedNavigation.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/widget/VisitedWidget.kt
feature/visited/src/main/res/values/strings.xml
feature/visited/src/test/kotlin/uk/govuk/app/visited/ExampleUnitTest.kt
feature/visited/src/test/kotlin/uk/govuk/app/visited/VisitedViewModelTest.kt

- The visited item display is currently undergoing a re-design for Android, so will be picked up as part of this follow up ticket: https://govukverify.atlassian.net/browse/GOVUKAPP-650.
- Currently, there is no visited item data. To be picked up as part of this follow up ticket: https://govukverify.atlassian.net/browse/GOVUKAPP-649.
- [GOVAPP-648](https://govukverify.atlassian.net/browse/GOVUKAPP-648)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-84052&node-type=frame&t=iPF2iHrJU5wud318-0)
```bash
Firebase event sent with: Bundle[{language=en, screen_class=VisitedScreen, screen_title=Pages you've visited, screen_name=Pages you've visited}]
Firebase event sent with: Bundle[{external=true, language=en, …
```

GOVUKAPP-648 : visited items - create list view

---

gradle.properties

The [docs](https://docs.gradle.org/current/userguide/configuration_cache.html) state that...
> configuration cache is a feature that significantly improves build performance by caching the result of the [configuration phase](https://docs.gradle.org/current/userguide/build_lifecycle.html#build_lifecycle) and reusing this for subsequent builds
I've found this to improve build performance locally, so adding it to the project seems like a nice development improvement.
Adding as a separate PR so that it's easy to revert - should we need to.

Set Gradle configuration-cache

---

feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/widget/VisitedWidget.kt

Padding should be 16.dp not 24.dp as it currently is.
- [GOVAPP-895](https://govukverify.atlassian.net/browse/GOVUKAPP-895)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-83650&node-type=canvas&t=nLINUAGLOTU5fEtF-0)
|---|---|
| ![padding-before-day](https://github.com/user-attachments/assets/b316062d-0ae0-4b8f-bf21-6f96b02960b4) | ![padding-before-night](https://github.com/user-attachments/assets/a45a2e5f-3392-4217-9aca-c934ad6a912b) |
|---|---|
| ![padding-after-day](https://github.com/user-attachments/assets/6b12b89e-d798-438f-9a03-e844a9efa450) | ![padding-after-night](https://github.com/user-attachments/assets/5054b747-358a-462c-9c63-2a9797e50013) |

Fix padding issue with visited items widget icon

---

analytics/src/main/kotlin/uk/govuk/app/analytics/Analytics.kt
analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt
analytics/src/test/kotlin/uk/govuk/app/analytics/AnalyticsClientTest.kt
app/src/main/kotlin/uk/govuk/app/Constants.kt
app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt
feature/settings/build.gradle.kts
feature/settings/src/main/kotlin/uk/govuk/app/settings/SettingsViewModel.kt
feature/settings/src/main/kotlin/uk/govuk/app/settings/navigation/SettingsNavigation.kt
feature/settings/src/main/kotlin/uk/govuk/app/settings/ui/SettingsScreen.kt
feature/settings/src/main/res/values/strings.xml
feature/settings/src/test/kotlin/uk/govuk/app/settings/SettingsViewModelTest.kt

This change:
- Redirects Help and feedback link from sub page to an external URL
- Adds external links and analytics handlers for:
- Help and feedback
- Privacy policy
- Accessibility statement
- Terms and conditions
- [GOVAPP-844](https://govukverify.atlassian.net/browse/GOVUKAPP-844)
- [GOVAPP-845](https://govukverify.atlassian.net/browse/GOVUKAPP-845)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-82977&node-type=canvas&t=4yA7SYm6CsHOqieL-0)
|---|---|
| ![settings-day](https://github.com/user-attachments/assets/c14dbd03-889a-4497-804a-b957a0966e12) | ![settings-night](https://github.com/user-attachments/assets/aa177299-e46c-411e-a725-f9a0b83bf60b) |
```bash
Firebase event sent with: …
```

Update settings links

---

feature/search/src/main/kotlin/uk/govuk/app/search/data/remote/SearchApi.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/remote/model/Result.kt
feature/search/src/main/kotlin/uk/govuk/app/search/domain/SearchConfig.kt
feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt
feature/search/src/test/kotlin/uk/govuk/app/search/domain/StringUtilsTest.kt

- [Search v1](https://www.gov.uk/api/search.json?q=micropig)
- [Search v2](https://search.publishing.service.gov.uk/v0_1/search.json?q=micropig)
- `description` in v1 has been renamed/moved to `description_with_highlighting`
- `description_with_highlighting` is an optional field
- [GOVAPP-833](https://govukverify.atlassian.net/browse/GOVUKAPP-833)

Switch Search API to V2

---

feature/visited/src/main/kotlin/uk/govuk/app/visited/VisitedClient.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/data/DateFormatter.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/data/VisitedItemsTransformer.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/data/store/VisitedLocalDataSource.kt
feature/visited/src/test/kotlin/uk/govuk/app/visited/VisitedClientTest.kt
feature/visited/src/test/kotlin/uk/govuk/app/visited/VisitedViewModelTest.kt
feature/visited/src/test/kotlin/uk/govuk/app/visited/data/DateFormatterTest.kt
feature/visited/src/test/kotlin/uk/govuk/app/visited/data/VisitedItemsTransformerTest.kt
feature/visited/src/test/kotlin/uk/govuk/app/visited/data/store/VisitedLocalDataSourceTest.kt

Ticket states:
> When user visits any content/services via the app (i.e. from search, topics, pages you’ve visited, etc), item is added to list on pages you’ve visited page (displayed with date stamp of last visited and sorted into appropriate time category). Scenario 2
The original implementation used a date stamp - which did not update the ordering as required above. To achieve the desired effect, we need a datetime stamp. This change updates the `VisitedItem.lastVisited` field as required.
- [GOVAPP-645](https://govukverify.atlassian.net/browse/GOVUKAPP-645)
- [GOVAPP-840](https://govukverify.atlassian.net/browse/GOVUKAPP-840)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-83650&node-type=canvas&t=n8xTlTVwGpZJ3YOd-0)

Change VisitedItem lastVisited from date to datetime stamp

---

app/build.gradle.kts

The original Global ON/OFF switch PR added a Compose Preview to a new UI file in the main app module.
The dependancy for Compose Preview was only available in the app to debug build variants.
This caused ALPHA build variants to fail building with an unknown resource error as the dependancy wasn't available to them.
To resolve we have made dependancy for Compose Preview available to ALL build variants.
- [GOVAPP-590](https://govukverify.atlassian.net/browse/GOVUKAPP-590)

GOVUKAPP-590 Global ON/OFF switch - Fix ALPHA build issue

---

feature/visited/src/main/kotlin/uk/govuk/app/visited/SectionTitles.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/data/DateFormatter.kt
feature/visited/src/test/kotlin/uk/govuk/app/visited/data/DateFormatterTest.kt

Visited items: minor context fixes:
- Don't capitalise the word `month` in `This month`
- Remove `year` from dates
- Change day of month from 2 digits to 1 or 2, so `1 October` not `01 October`

Visited items minor content fixups

---

design/src/main/kotlin/uk/govuk/app/design/ui/component/Button.kt

It was observed in Post Amigos that when large text size is set that a button text with external link icon causes the link icon to resize very small.
Added a weight modifier to button text to resolve this.
|---|---|
| ![image](https://github.com/user-attachments/assets/49cb333e-9530-499b-aa42-208eaf79eeb0) | ![image](https://github.com/user-attachments/assets/a89a001d-4e23-4d80-a1b4-40ceffe2c4a7) |
|---|---|
| ![image](https://github.com/user-attachments/assets/1f1e3729-8a75-4e21-98fc-7c1296482253) | ![image](https://github.com/user-attachments/assets/4f2b7bbc-614a-4475-954b-f61eb0d76470) |

GOVUKAPP-590 Global ON/OFF switch - Post Amigos fix

---

design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/VisitedViewModel.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/navigation/VisitedNavigation.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt
feature/visited/src/main/res/values/strings.xml
feature/visited/src/test/kotlin/uk/govuk/app/visited/VisitedViewModelTest.kt

This change adds the edit screen for visited items. 
It also fixes a padding issue [identified here](https://govukverify.atlassian.net/browse/GOVUKAPP-645) on the view screen.
Visited items on the edit screen retain  the link colouration for the title and `open in...` icon from the view screen. However, the link is no longer clickable and the alt text for the icon has been removed. This is in-line with the iOS implementation.
This change does not address:
- Removing visited items from the Realm database
- Selecting and deselecting all visited items
- Removing all visited items
- The `Select all` and `Remove` button logic 
All of the above will be addressed in [this ticket](https://govukverify.atlassian.net/browse/GOVUKAPP-652).
- …

Android | Visited items: Create edit mode

---

feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt

Bug: Onboarding slides off-centre.
When navigating Onboarding slides using a keyboard the text and image becomes off-centre.
Set horizontal padding on the columns children rather than the column.
- [GOVAPP-961](https://govukverify.atlassian.net/browse/GOVUKAPP-961)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-53780&node-type=canvas&t=OsppmOx5g6akleui-0)
|---|---|
| ![Screenshot_1732283706](https://github.com/user-attachments/assets/dd9be54b-6830-4692-8b4f-303779e533a5) | ![image](https://github.com/user-attachments/assets/eb6221f2-1452-4a2e-a707-7548d93f3388) |
|---|---|
| ![image](https://github.com/user-attachments/assets/9b7ca7eb-82e2-4dca-a29c-c01d0de5208a) | …

GOVUKAPP-961 Onboarding slides off-centre

---

feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt

Following discussions with Design (ER) where various options were presented, the chosen solution is to move the header into the scrolling part of the content - so that goes behind the header, and the header is centered. Both the list and edit `Pages you've visited` pages have been updated. The title text now performs as desired.
It was suggested that maintaining the `Opens in browser...` icons for each visited item be remove in the Edit view as clicking on a visited item in this view selects or deselects. It does not `Open in browser...`. 
- [GOVAPP-646](https://govukverify.atlassian.net/browse/GOVUKAPP-646)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-84094&node-type=frame&t=yHDV5lKHdGAe4yF1-0)
🎶  In these screen shots …

Post amigo edit visited item changes

---

feature/visited/src/main/kotlin/uk/govuk/app/visited/data/VisitedItemsTransformer.kt
feature/visited/src/test/kotlin/uk/govuk/app/visited/data/VisitedItemsTransformerTest.kt

The call to the `capitaliseMonth` function in the VisitedItemsTransformer somehow got removed at some point - add it back in.
- [GOVAPP-993](https://govukverify.atlassian.net/browse/GOVUKAPP-993)
🎶  Note the use of fake data here!
|---|---|
| ![month-before](https://github.com/user-attachments/assets/75de6973-4868-4ed0-9256-a875c54e144b) | ![month-after](https://github.com/user-attachments/assets/8b2feef6-554a-4c4c-ad6b-45ee439fec89) |

GOVUKAPP-993 - Capitalisation of months

---

feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt

The last visited item in the list is being hidden or obscured by the bottom nav bar. Increase spacing below last visited list item.
|---|---|
| ![pyv-list-before](https://github.com/user-attachments/assets/7da7f71c-3cec-4d24-ac2f-fd814511869c) | ![pyv-list-after](https://github.com/user-attachments/assets/fcd16ec4-befc-4b91-9055-465616e45c9a) |

Bug fix - last visited item being hidden or obscured by the bottom nav bar

---

feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt

Remove padding if search result has no description
- [GOVUKAPP-999](https://govukverify.atlassian.net/browse/GOVUKAPP-999)
[GOVUKAPP-999]: https://govukverify.atlassian.net/browse/GOVUKAPP-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-999: Search result padding no description

---

app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt

Padding at bottom of PYV list is different on edit and non edit mode
Pass padding values for tab bar etc into visited screen so visited screen padding can be set correctly
- [GOVAPP-1012](https://govukverify.atlassian.net/browse/GOVUKAPP-1012)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=3245-19697&node-type=frame&t=SuOEuXkoh7K39MQp-0)
| Normal Mode | Edit Mode |
|---|---|
| ![image](https://github.com/user-attachments/assets/9bc310d7-84a4-4281-8603-d299b82ad6b2) | ![image](https://github.com/user-attachments/assets/2a11f6b9-07fb-4273-b4f5-9469b71b4cda) |
| Normal Mode | Edit Mode |
|---|---|
| ![image](https://github.com/user-attachments/assets/eedecf71-dd3c-459f-a0a9-132c52f68c3f) | …

GOVUKAPP-1012 Inconsistent padding

---

feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt

Hide the keyboard when the user searches for search term
- [GOVAPP-1008](https://govukverify.atlassian.net/browse/GOVUKAPP-1008)
|---|---|
| [search-keyboard-before.webm](https://github.com/user-attachments/assets/37d4bce6-8d8e-4bb7-b7d8-1a3e540ea999) | [search-keyboard-after.webm](https://github.com/user-attachments/assets/cc811639-6cb0-432a-98f9-60747e89ffa6) |

GOVUKAPP-1008 :  Keyboard obscures search results

---

design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/AllStepByStepsScreen.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/AllTopicsScreen.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/EditTopicsScreen.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicScreen.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt
feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt

ChildPageHeader component updated to handle optional Back (left hand side) button, 'action' (right hand side) button, and header text.
- [GOVAPP-1001](https://govukverify.atlassian.net/browse/GOVUKAPP-1001)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-83650&node-type=canvas&t=wNQf4guNUFZXVKUN-0)
| ChildPageHeader Previews |
|---|
| ![Screenshot 2024-12-09 at 11 53 21](https://github.com/user-attachments/assets/57b4a746-91b7-4a20-aec5-cc3de98688e7) |
| List Screen | Edit Screen |
|---|---|
| ![list-screen](https://github.com/user-attachments/assets/df490c34-1b1e-4708-a378-3ac732ef0d30) | ![edit-screen](https://github.com/user-attachments/assets/2a3d6222-842b-4eed-bd5e-85c42136fb9e) |

GOVUKAPP-1001: pages you've visited should ChildPageHeader

---

analytics/src/main/kotlin/uk/govuk/app/analytics/ui/AnalyticsConsentScreen.kt

Description
- [GOVAPP-1015](https://govukverify.atlassian.net/browse/GOVUKAPP-1015)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-65919&node-type=frame&t=fYBpuivAbDg9jGKS-0)
|---|---|
| ![consent-before](https://github.com/user-attachments/assets/9f17f0d4-b0cc-4a88-be3a-471c89d11afe) | ![consent-after](https://github.com/user-attachments/assets/9b2ddec3-1baa-4313-9eb5-9753eec1c60e) |
|---|---|
| ![consent-before-ls](https://github.com/user-attachments/assets/060e5977-f1f1-4af1-827f-3fc7761585de) | ![consent-after-ls](https://github.com/user-attachments/assets/2dc7e89d-9549-4a28-8218-b2c18b760998) |

GOVUKAPP-1015 : Analytics consent link icon position

---

feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt

- [GOVAPP-1010](https://govukverify.atlassian.net/browse/GOVUKAPP-1010)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-74994&node-type=canvas&t=fYBpuivAbDg9jGKS-0)
|---|---|
| ![spacing-before](https://github.com/user-attachments/assets/846edded-7553-4acc-9806-f84673989d87) | ![spacing-after](https://github.com/user-attachments/assets/4360e875-777e-4ade-8785-c8064ed3b755) |

GOVUKAPP-1010 : Padding around "open in browser" icon

---

feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt

Disable cell selection indicator in edit mode
- [GOVUKAPP-1011](https://govukverify.atlassian.net/browse/GOVUKAPP-1011)
[Screen_recording_20241212_111231.webm](https://github.com/user-attachments/assets/f1ae5370-867b-4123-a97f-0aaec2dcf6c1)
[Screen_recording_20241212_111128.webm](https://github.com/user-attachments/assets/05e0049c-ced5-4d42-b404-78760c6c10b6)
[GOVUKAPP-1011]: https://govukverify.atlassian.net/browse/GOVUKAPP-1011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1011: PYV Edit Selection Bug

---

feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt

Focus of page title labels was being requested on instances of further pages than the current one causing the pager to skip to the further pages 
Only request focus of page title on current page
- [GOVAPP-1009](https://govukverify.atlassian.net/browse/GOVUKAPP-1009)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-53780&node-type=canvas&t=VGAdGIeB8VjkoH3y-0)
https://github.com/user-attachments/assets/faae8c68-7979-46b0-aea6-c3d46996210e
https://github.com/user-attachments/assets/220387ed-8464-463f-883b-6d0ac7bebfa4

GOVUKAPP-1009 Onboarding screens missed when using swipe to navigate

---

feature/search/build.gradle.kts
feature/search/src/main/kotlin/uk/govuk/app/search/SearchUiState.kt
feature/search/src/main/kotlin/uk/govuk/app/search/SearchViewModel.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/SearchRepo.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/local/SearchDataStore.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/local/SearchEncryptionHelper.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/local/SearchLocalDataSource.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/local/SearchRealmProvider.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/local/model/LocalSearchItem.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/remote/model/SearchResponse.kt
feature/search/src/main/kotlin/uk/govuk/app/search/data/remote/model/SearchResult.kt
feature/search/src/main/kotlin/uk/govuk/app/search/domain/SearchConfig.kt
feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchErrors.kt
feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchResults.kt
feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt
feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchSuggestions.kt
feature/search/src/main/kotlin/uk/govuk/app/search/ui/component/Header.kt
feature/search/src/main/kotlin/uk/govuk/app/search/ui/component/TextField.kt
feature/search/src/main/res/values/strings.xml
feature/search/src/test/kotlin/uk/govuk/app/search/SearchViewModelTest.kt
feature/search/src/test/kotlin/uk/govuk/app/search/data/SearchRepoTest.kt
feature/search/src/test/kotlin/uk/govuk/app/search/data/local/SearchDataStoreTest.kt
feature/search/src/test/kotlin/uk/govuk/app/search/data/local/SearchLocalDataSourceTest.kt

Previous searches
- [GOVUKAPP-1031](https://govukverify.atlassian.net/browse/GOVUKAPP-1031)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=3405-22081&t=abFJMvL1ZmmKVVB2-4)
[GOVUKAPP-1031]: https://govukverify.atlassian.net/browse/GOVUKAPP-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1031: Previous searches

---

feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt

When you click on an autocomplete suggestion it doesn't populate the search bar with the suggestion. Instead, it leaves what you've typed. For example: type `dog` and select the `dog breeding` suggestion - the search bar stays as `dog`.

Autocomplete select bug fix

---

app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt

The bottom navigation selected icon colour should remained `Blue1` not `Green1`
| Before| After |
|---|---|
| ![light-after-page-6](https://github.com/user-attachments/assets/1b4167ce-a69f-42af-a6ab-5332be9841e8) | ![light-after-home](https://github.com/user-attachments/assets/fed3b774-88ba-40e8-aa64-654943de8399) |
| ![light-after-page-7](https://github.com/user-attachments/assets/4af474e4-a9d9-4bec-a6e7-3477f00fa30d) | ![light-after-settings](https://github.com/user-attachments/assets/f11b2e40-30a2-4b03-8f39-fbca3fa357a3) |
| ![dark-after-page-6](https://github.com/user-attachments/assets/da4f993d-b1f0-458d-99cd-93f3a7692da0) | ![dark-after-home](https://github.com/user-attachments/assets/15982656-caa8-4a35-b5a2-a26c357d45b4) |
| …

Bottom navigation selected icon colour bug fix

---

design/src/main/kotlin/uk/govuk/app/design/ui/component/List.kt
design/src/main/kotlin/uk/govuk/app/design/ui/component/Switch.kt

This effectively means that we are unable to create Maestro tests that either assert on a particular state , or seek to update the current state of these elements.
This change adds a `resource-id` which uniquely identifies each ToggleSwitch instance.
- [GOVAPP-1107](https://govukverify.atlassian.net/browse/GOVUKAPP-1107)

Maestro is unable to find and interact with our ToggleSwitch component implementation

---

analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt
analytics/src/main/kotlin/uk/govuk/app/analytics/FirebaseAnalyticsClient.kt
analytics/src/test/kotlin/uk/govuk/app/analytics/AnalyticsClientTest.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/AllStepByStepsViewModel.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicViewModel.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/navigation/TopicsNavigation.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/AllStepByStepsScreen.kt
feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicScreen.kt
feature/topics/src/test/kotlin/uk/govuk/app/topics/AllStepByStepsViewModelTest.kt
feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicViewModelTest.kt

Fixes an issue where the `select_item` event `index` value is not represented correctly. It should be the position of the item that was clicked (in the previous `visited_item_list` for example), and not its position in the result set (which would always be 1).
This requirement was initially missing in the ticket, and did not surface in conversations with performance analysts.
- [GOVUKAPP-1143](https://govukverify.atlassian.net/browse/GOVUKAPP-1143)
```shell
name=select_item,
params=Bundle[
{
item_list_name=Topics,
item_list_id=Benefits,
items=[
Bundle[
{
item_name=Universal Credit,
index=1,
item_category=Popular pages in this topic,
location_id=https://www.gov.uk/universal-credit
}
]
],
results=1
}
```
```shell
name=select_item,
params=Bundle[
{
item_list_name=Topics, …
```

GOVUKAPP-1143: select_item event index is not represented correctly

---

feature/search/src/main/kotlin/uk/govuk/app/search/ui/PreviousSearches.kt

`Delete` in the "Delete previous searches?" dialog was `buttonRemove` or `Red1` (D4351C) in light and dark mode. 
This has now been changed to `buttonDestructive`. So is now `RedPrimary` (CA3535) in light mode and `RedAccent` (FF5E5E) in dark mode.
- [GOVUKAPP-1206](https://govukverify.atlassian.net/browse/GOVUKAPP-1206)
|---|---|
|   |   |
| ![before-light](https://github.com/user-attachments/assets/43e0b623-9fdb-4145-9b31-e7ca20575273) | ![after-light](https://github.com/user-attachments/assets/c1bcbb1a-4449-4a89-a307-4198037d28fd) |
| ![before-dark](https://github.com/user-attachments/assets/7dd9658a-4c56-4bf4-861b-b2b87433c3ef) | ![after-dark](https://github.com/user-attachments/assets/787045f0-1e54-4be6-ab86-32ad5df711c6) |
[GOVUKAPP-1206]: …

GOVUKAPP-1206: Update delete text colour in delete previous searches dialog

---

feature/search/src/main/kotlin/uk/govuk/app/search/ui/PreviousSearches.kt
feature/search/src/main/res/values/strings.xml

Amend duplicated content description string names in 2 modules to fix incorrect string being used
- [GOVUKAPP-1099](https://govukverify.atlassian.net/browse/GOVUKAPP-1099)
[GOVUKAPP-1099]: https://govukverify.atlassian.net/browse/GOVUKAPP-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1099 Homepage notification upsell talkback fix

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/uk/gov/govuk/MainActivity.kt
app/src/main/kotlin/uk/gov/govuk/navigation/AppLaunchNavigation.kt
app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt
app/src/test/kotlin/uk/gov/govuk/navigation/AppLaunchNavigationTest.kt
feature/home/src/main/kotlin/uk/gov/govuk/home/navigation/HomeNavigation.kt
feature/search/src/main/kotlin/uk/gov/govuk/search/navigation/SearchNavigation.kt
feature/settings/src/main/kotlin/uk/gov/govuk/settings/navigation/SettingsNavigation.kt
feature/topics/src/main/kotlin/uk/gov/govuk/topics/navigation/TopicsNavigation.kt
feature/visited/src/main/kotlin/uk/gov/govuk/visited/navigation/VisitedNavigation.kt

- Add compose deeplinks.
- Add logic for handling deeplinks from cold start, background and foreground.
- Set 'Topics All Route' as start destination for Topics instead of 'Topics Selection' as that works better in the nav graph when deeplinking to Topics screens.
- [GOVUKAPP-1133](https://govukverify.atlassian.net/browse/GOVUKAPP-1133)
[GOVUKAPP-1133]: https://govukverify.atlassian.net/browse/GOVUKAPP-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1133 App deeplinks from notification

---

feature/local/consumer-rules.pro
feature/local/src/main/kotlin/uk/govuk/app/local/LocalViewModel.kt
feature/local/src/main/kotlin/uk/govuk/app/local/data/remote/model/LocalAuthority.kt

This is mostly due to the local authority parent and consumer-rules.pro file paths being incorrect and the local authority parent not being serialised.

Fixes a bug where local authorities are not showing in the app

---

design/src/main/kotlin/uk/gov/govuk/design/ui/component/List.kt

- Update the notifications status font in settings.
- Remove the chevron in notifications in settings.
- [GOVUKAPP-1479](https://govukverify.atlassian.net/browse/GOVUKAPP-1479)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs)
| ![Screenshot_1744290975](https://github.com/user-attachments/assets/6f9be823-26ab-4cbc-845e-b6bd38b7a628) | ![Screenshot_1744290490](https://github.com/user-attachments/assets/0d61ac56-3583-4de3-84b2-f46abe93e883) |
[GOVUKAPP-1479]: https://govukverify.atlassian.net/browse/GOVUKAPP-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1479 Update font size for "off" button

---

notifications/src/main/kotlin/uk/gov/govuk/notifications/ui/NotificationsOnboardingScreen.kt

Add a header with back button to notifications onboarding screen
- [GOVUKAPP-1480](https://govukverify.atlassian.net/browse/GOVUKAPP-1480)
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-apps-and-notifications?node-id=22321-13370&t=ogZnHZYMfvcnFQ0e-1)
| ![Screenshot_1744367028](https://github.com/user-attachments/assets/048e0ed7-de6a-49bd-9cdf-c606aa92cadc) | ![Screenshot_1744366985](https://github.com/user-attachments/assets/0facbb96-dbb3-4b1f-aa5a-028fc4d39dce) |
[GOVUKAPP-1480]: https://govukverify.atlassian.net/browse/GOVUKAPP-1480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1480 Add back button behaviour for notifications education screen

---

design/src/main/kotlin/uk/gov/govuk/design/ui/theme/Color.kt
feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalEntryScreen.kt
feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalWidget.kt

Renames, where needed, the colour tokens used and applies the appropriate section and Android naming convention.
- localIcon renamed to iconGreen
- localBackground renamed to cardGreen
- textFieldBackground no change needed
- highlightedTextField renamed to textFieldHighlighted
- localBorder renamed to cardGreen
- textFieldCursor no change needed
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-apps-and-notifications?node-id=20393-21993&p=f&t=JMkRrXdgeNT0PUsI-0)

Update colour tokens to bring them in-line with Figma

---

feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalWidget.kt
feature/topics/src/main/kotlin/uk/gov/govuk/topics/ui/widget/TopicsWidget.kt

Fix for edit button on topics and local widget when font and display size is increased

Home widget edit button fix

---

app/src/androidTest/kotlin/uk/gov/govuk/MainActivityTest.kt
app/src/main/kotlin/uk/gov/govuk/MainActivity.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsClient.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsClientTest.kt

- If Gson cannot parse the Additional Data sent from One SIgnal notifications then send the app an intent with an empty Uri. This is so the Uri passes through the Uri validation route and results in Page Not Found alert being presented to the user as required.
- Remove redundant `emitIntent()` function from MainActivity as found during testing that it's not needed.
- [GOVUKAPP-1523](https://govukverify.atlassian.net/browse/GOVUKAPP-1523)
[GOVUKAPP-1523]: https://govukverify.atlassian.net/browse/GOVUKAPP-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1523 Notification deep links that cannot be parsed

---

feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalEntryScreen.kt

- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-apps-and-notifications?node-id=20393-21993&p=f&t=XIz8NXrPzjRIgWgL-0)
| ![invalid-before-light](https://github.com/user-attachments/assets/ee1b292e-ed03-4ad9-9d36-31b0e6bd3a74) | ![invalid-after-light](https://github.com/user-attachments/assets/c7aeaa2e-64d8-4861-ae26-cf3832e97b07) |
| ![invalid-before-dark](https://github.com/user-attachments/assets/300983fe-c1b2-4d5a-87ec-e4dfd189a102) | ![invalid-after-dark](https://github.com/user-attachments/assets/031e13b1-068d-46f2-a253-b20293757586) |
| ![not-found-before-light](https://github.com/user-attachments/assets/d4e6805a-3d7e-4dc8-98c7-3e2f232d0fc5) | ![not-found-after-light](https://github.com/user-attachments/assets/440eab41-4f …

Fix error state text colour

---

app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt
config/src/main/kotlin/uk/gov/govuk/config/data/flags/FlagRepo.kt
feature/settings/src/main/kotlin/uk/gov/govuk/settings/navigation/SettingsNavigation.kt
notifications/build.gradle.kts
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsOnboardingViewModel.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/data/NotificationsRepo.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/data/local/NotificationsDataStore.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/navigation/NotificationsNavigation.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/ui/NotificationsOnboardingScreen.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsOnboardingViewModelTest.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/data/NotificationsRepoTest.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/data/local/NotificationsDataStoreTest.kt

- Only show the notifications consent screen on app launch once
- Add notifications consent logic for Android < 33 devices
- Ensure notifications onboarding screen not shown when feature flag is turned off
- [GOVUKAPP-1594](https://govukverify.atlassian.net/browse/GOVUKAPP-1594)
[GOVUKAPP-1594]: https://govukverify.atlassian.net/browse/GOVUKAPP-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1594 Update notifications consent behaviour

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml

Prepare app ready for release by resolving Google Play console warnings for:
[Disable collection of advertising ID doc](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android#disable_advertising_id_collection)
[Include debug symbols doc](https://developer.android.com/reference/tools/gradle-api/8.3/null/com/android/build/api/dsl/Ndk)
- [GOVUKAPP-1691](https://govukverify.atlassian.net/browse/GOVUKAPP-1691)
[GOVUKAPP-1691]: https://govukverify.atlassian.net/browse/GOVUKAPP-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1691 Prevent advertising id collection and include debug symbols

---

feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalEntryScreen.kt
feature/local/src/main/res/values/strings.xml

- [GOVUKAPP-1712](https://govukverify.atlassian.net/browse/GOVUKAPP-1712)
| ![Screenshot_20250519_084729](https://github.com/user-attachments/assets/52197b34-27a5-4d3c-a7f7-f470dbcd4681) | ![Screenshot_20250519_084256](https://github.com/user-attachments/assets/6f2d8b06-af4d-4d12-a43b-42c40c469055) |
[GOVUKAPP-1712]: https://govukverify.atlassian.net/browse/GOVUKAPP-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1712 : Remove first paragraph on local postcode entry screen

---

feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalEntryScreen.kt

- [GOVUKAPP-1659](https://govukverify.atlassian.net/browse/GOVUKAPP-1659)
| ![before](https://github.com/user-attachments/assets/9969b5d9-99b9-43c3-834d-dadecbd27a0b) | ![after](https://github.com/user-attachments/assets/ec39b95a-8dee-47d3-b5e8-b149a6564298) |
[GOVUKAPP-1659]: https://govukverify.atlassian.net/browse/GOVUKAPP-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1659 : Disable confirm postcode button until the user has entered at least one character

---

feature/topics/src/main/kotlin/uk/gov/govuk/topics/ui/TopicScreen.kt

Change topic description colours and spacing to match designs
- [GOVUKAPP-1757](https://govukverify.atlassian.net/browse/GOVUKAPP-1757)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=2540-16871&t=wm8Fpa0PrONSwAAN-0)
| ![Screenshot_1747825735](https://github.com/user-attachments/assets/4654257c-9b3f-474e-8a44-b94052b3d33a) | ![Screenshot_1747827065](https://github.com/user-attachments/assets/49bfb62f-cf29-4f19-a6bd-e5ab2da1ff03) |
[GOVUKAPP-1757]: https://govukverify.atlassian.net/browse/GOVUKAPP-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1757 Topic description colour change to match designs

---

design/src/main/kotlin/uk/gov/govuk/design/ui/component/Onboarding.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/ui/NotificationsOnboardingScreen.kt

Remove privacy notice link from onboarding screens as accidentally added by notifications onboarding task
- [GOVUKAPP-1759](https://govukverify.atlassian.net/browse/GOVUKAPP-1759)
| ![Screenshot_1747835463](https://github.com/user-attachments/assets/5321c8df-5f89-43f4-93f0-c9077eaa8b76) | ![Screenshot_1747835294](https://github.com/user-attachments/assets/7abb963a-307c-4d48-8334-3f9b2d13a7f0) | 
[GOVUKAPP-1759]: https://govukverify.atlassian.net/browse/GOVUKAPP-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1759 Privacy notice link

---

app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsClient.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsConsentViewModel.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsOnboardingViewModel.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsPermissionViewModel.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsViewModel.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/navigation/NotificationsNavigation.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/ui/NotificationsConsentScreen.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/ui/NotificationsOnboardingScreen.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/ui/NotificationsPermissionScreen.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsClientTest.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsConsentViewModelTest.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsOnboardingViewModelTest.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsPermissionViewModelTest.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsViewModelTest.kt

- Add finish function to view models to avoid callbacks being fired twice
- Add remove consent function and check and set it on app launch and on notification permission changes
- [GOVUKAPP-1604](https://govukverify.atlassian.net/browse/GOVUKAPP-1604)
[GOVUKAPP-1604]: https://govukverify.atlassian.net/browse/GOVUKAPP-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1604 Notifications permission navigation

---

analytics/src/main/AndroidManifest.xml
app/src/main/AndroidManifest.xml

Remove advertising id permission added by Google Analytics as redundant
- [GOVUKAPP-1769](https://govukverify.atlassian.net/browse/GOVUKAPP-1769)
[GOVUKAPP-1769]: https://govukverify.atlassian.net/browse/GOVUKAPP-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1769 Remove advertising id permission added by GA

---

app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt
config/src/main/kotlin/uk/gov/govuk/config/data/flags/FlagRepo.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsConsentViewModel.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/NotificationsPermissionViewModel.kt
notifications/src/main/kotlin/uk/gov/govuk/notifications/ui/NotificationsPermissionScreen.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsConsentViewModelTest.kt
notifications/src/test/kotlin/uk/gov/govuk/notifications/NotificationsPermissionViewModelTest.kt

- Remove hardcoded FALSE from notifications debug flag so notifications is on in debug builds. 
- Remove OneSignal consent when continue to device settings button is pressed and rework logic around it.
- [GOVUKAPP-1853](https://govukverify.atlassian.net/browse/GOVUKAPP-1853)
[GOVUKAPP-1853]: https://govukverify.atlassian.net/browse/GOVUKAPP-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1853 Turn OneSignal consent off when continue to device settings clicked

---

feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalLookupScreen.kt
feature/local/src/main/res/values/strings.xml

Add content description to postcode entry textfield
Content description was intentionally applied to the TextField placeholder Text as it read 'Postcode' out twice when applied directly to the TextField and so sounded odd.
- [GOVUKAPP-1912](https://govukverify.atlassian.net/browse/GOVUKAPP-1912)
https://github.com/user-attachments/assets/9d8ef65f-aee7-4f28-9875-2e0612cb204e
[GOVUKAPP-1912]: https://govukverify.atlassian.net/browse/GOVUKAPP-1912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1912 Info and relationships - What is your postcode?

---

data/build.gradle.kts
data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt
gradle/libs.versions.toml

- Update browser library and set ephemeral browsing enabled on browser that presents One Login
- Note: there are newer alpha browser versions than 1.9.0-alpha01 but they require a compile version of 36 and our is currently 35. We will be targeting 36 in the future.
- [GOVUKAPP-1947](https://govukverify.atlassian.net/browse/GOVUKAPP-1947)
[GOVUKAPP-1947]: https://govukverify.atlassian.net/browse/GOVUKAPP-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1947 Cached cognito request

---

feature/topics/src/main/kotlin/uk/gov/govuk/topics/ui/TopicScreen.kt

Check if topic heading is visible before requesting focus on it
- [GOVUKAPP-1908](https://govukverify.atlassian.net/browse/GOVUKAPP-1908)
[GOVUKAPP-1908]: https://govukverify.atlassian.net/browse/GOVUKAPP-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-1908 Fix focus requester crash

---

app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt

- I have been unable to reproduce this crash and it didn't appear during initial dev testing of notifications.
- Currently we read properties and call functions on navcontroller in OnResume. 
- Code has been refactored in this change so the current instance of navcontroller is always read as we are reading it during lifecycle events when new objects could be instantiated.
- Add a try-catch to check that the navcontroller has a nav graph set.
- Move functions which call the navcontroller into the scope where the navhost is instantiated - _I suspect this is the actual reason for the crash that the navcontrollers properties and functions are read and called before navhost has been instantiated_.
- Also made the same change for currently commented out code that handles received intents. …

GOVUKAPP-2067 Navigation crash

---

data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt
data/src/test/kotlin/uk/gov/govuk/data/auth/AuthRepoTest.kt

- Set supported authenticators for different Android versions to enable biometrics on BIOMETRICS_STRONG devices running pre Android 11 (SDK 30)
- [GOVUKAPP-2149](https://govukverify.atlassian.net/browse/GOVUKAPP-2149)
[GOVUKAPP-2149]: https://govukverify.atlassian.net/browse/GOVUKAPP-2149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-2149 Enable biometrics for devices running Android 9 or 10

---

feature/chat/src/main/kotlin/uk/gov/govuk/chat/ChatViewModel.kt
feature/chat/src/main/kotlin/uk/gov/govuk/chat/data/ChatRepo.kt
feature/chat/src/main/kotlin/uk/gov/govuk/chat/data/local/ChatDataStore.kt
feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt
feature/chat/src/main/res/values/strings.xml
feature/chat/src/test/kotlin/uk/gov/govuk/chat/ChatViewModelTest.kt
feature/chat/src/test/kotlin/uk/gov/govuk/chat/data/ChatRepoTest.kt
feature/chat/src/test/kotlin/uk/gov/govuk/chat/data/local/ChatDataStoreTest.kt

The retryable error page should only be shown on 404 (Not Found) errors, PII errors show a suitable message, all other errors should show the non-retryable error page (see screenshots below).
- [GOVUKAPP-2137](https://govukverify.atlassian.net/browse/GOVUKAPP-2137)
- [GOVUKAPP-2045](https://govukverify.atlassian.net/browse/GOVUKAPP-2045) - provides backend implementation for clearing the conversation, not the UI aspects of this ticket
- [Figma](https://www.figma.com/design/rKYEySuNc8aikJWYfEz1wR/2025-04-GOV.UK-Chat-and-AI?node-id=4593-43523&t=k8nL9IKwKYFaDwPw-0)
| Retryable | Non-retryable |
| <img width="1080" height="2424" alt="light-404" src="https://github.com/user-attachments/assets/5bf43c2e-4713-4f88-a143-02342cd64db0" /> | <img width="1080" height="2424" …

GOVUKAPP-2137 : Add retryable error page

---

app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt

I believe devices that are affected by this crash are devices that are closing activities when apps are backgrounded to free up memory.
Steps to reproduce:
- In Developer options turn 'Don't keep Activities' to ON.
- Run the app and sign in.
- Background the app and wait until user interaction timeout (so sign out occurs).
- Observe crash in Firebase (I did not receive any indication on my device that the app had crashed).
Fix:
- Prevent navigation when the app view model has already been cleared.
- [GOVUKAPP-2181](https://govukverify.atlassian.net/browse/GOVUKAPP-2181)
Stacktrace:
Fatal Exception: java.lang.IllegalStateException
State must be at least CREATED to move to DESTROYED, but was INITIALIZED in component NavBackStackEntrydestination=ComposeNavGraph(0x0) …

GOVUKAPP-2181 Sign out crash

---

design/src/main/kotlin/uk/gov/govuk/design/ui/theme/Color.kt
feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt
feature/chat/src/main/res/drawable/baseline_circle_24.xml
feature/chat/src/main/res/values/strings.xml

- [Figma](https://www.figma.com/design/rKYEySuNc8aikJWYfEz1wR/2025-04-GOV.UK-Chat-and-AI?node-id=4930-49082&t=x0DMsWRNtPyDcFHU-0)
| Light | Dark |
| <img width="1080" height="2424" alt="light" src="https://github.com/user-attachments/assets/d11c16a6-2053-406e-9011-1b799d5b64a3" /> | <img width="1080" height="2424" alt="dark" src="https://github.com/user-attachments/assets/b0cb1a25-3e06-4734-840c-5504a9c14723" /> |
https://github.com/user-attachments/assets/3849ecfd-2cf2-49d2-8d6a-9c67b0d21e84

Fix 'generating answer' : Add shimmering text and apply to loading state text

---

app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt
app/src/main/kotlin/uk/gov/govuk/di/LoginModule.kt
app/src/main/kotlin/uk/gov/govuk/login/LoginViewModel.kt
app/src/main/kotlin/uk/gov/govuk/login/data/LoginRepo.kt
app/src/main/kotlin/uk/gov/govuk/login/data/local/LoginDataStore.kt
app/src/test/kotlin/uk/gov/govuk/AppViewModelTest.kt
app/src/test/kotlin/uk/gov/govuk/login/LoginViewModelTest.kt
app/src/test/kotlin/uk/gov/govuk/login/data/LoginRepoTest.kt
app/src/test/kotlin/uk/gov/govuk/login/data/local/LoginDataStoreTest.kt
data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt

On successful auth response save the ID token issue date and time locally. 
On future app launches, check that the stored date and time is greater than 6 days 23 hours of the current date and time before prompting for biometric login else sign the user out.
- [GOVUKAPP-2206](https://govukverify.atlassian.net/browse/GOVUKAPP-2206)
[GOVUKAPP-2206]: https://govukverify.atlassian.net/browse/GOVUKAPP-2206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-2208 Handle expired refresh tokens

---

app/src/main/kotlin/uk/gov/govuk/login/BiometricSettingsViewModel.kt
app/src/main/kotlin/uk/gov/govuk/login/ui/BiometricSettingsScreen.kt
app/src/main/res/values/strings.xml
app/src/test/kotlin/uk/gov/govuk/login/BiometricSettingsViewModelTest.kt

Add 2 biometric settings descriptions (1 for Android <10 and 1 for Android 11>) and the logic to show them
- [GOVUKAPP-2304](https://govukverify.atlassian.net/browse/GOVUKAPP-2304)
| Android 10 Before | Android 10 After |
| <img width="1080" height="2280" alt="Screenshot_1755615597" src="https://github.com/user-attachments/assets/2af8e439-a655-4957-b869-474832226370" /> | <img width="1080" height="2280" alt="Screenshot_1755615132" src="https://github.com/user-attachments/assets/0bf1129d-0f1f-4085-acf3-2d6693aeeffd" /> |
| Android 11 Before | Android 11 After |
| <img width="1344" height="2992" alt="Screenshot_1755615570" src="https://github.com/user-attachments/assets/6393c7b0-aa60-47fb-bb43-4c0ee9d53da3" /> | <img width="1344" height="2992" …

GOVUKAPP-2304 Update biometrics settings screen

---

design/src/main/kotlin/uk/gov/govuk/design/ui/theme/Color.kt

Add 'blue-darkmode' colour to Alert Card background
- [GOVUKAPP-2461](https://govukverify.atlassian.net/browse/GOVUKAPP-2461)
- [Figma board](https://www.figma.com/design/x5i4a5RT0xMhJAcjoIxefb/2025-06-GOV.UK-app-library-v2--UX-refresh?node-id=9045-5307&t=dnrzWfnQZnxk2nrj-0)
| <img width="300" height="668" alt="Screenshot_1756718873" src="https://github.com/user-attachments/assets/164f9f70-2aee-4f31-99bd-f3555a37d6d4" /> | <img width="300" height="668" alt="Screenshot_1756718371" src="https://github.com/user-attachments/assets/f0c58b39-5795-410a-abf6-2aa979d2dc2a" /> |
[GOVUKAPP-2461]: https://govukverify.atlassian.net/browse/GOVUKAPP-2461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-2461 Dark mode blue to Alert Card

---

feature/settings/src/main/kotlin/uk/gov/govuk/settings/ui/SignOutScreen.kt
feature/settings/src/main/res/values/strings.xml

Update sign out content
- [GOVUKAPP-2468](https://govukverify.atlassian.net/browse/GOVUKAPP-2468)
(Figma for this screen is out of date and doesn't have these changes yet. Will comment this on the Jira)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=6429-9112&p=f&t=9kUFZDAKjkayAU9K-0)
| <img width="1344" height="2992" alt="image" src="https://github.com/user-attachments/assets/b6fd48bf-85ee-4cf2-a2c8-e87a947926d2" /> | <img width="1344" height="2992" alt="image" src="https://github.com/user-attachments/assets/8e744624-ac42-4220-ade0-b1728c413140" /> |
[GOVUKAPP-2468]: https://govukverify.atlassian.net/browse/GOVUKAPP-2468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

GOVUKAPP-2468 Sign out content change

---

app/src/main/kotlin/uk/gov/govuk/ui/BrowserLauncher.kt

Set flag on intents to prevent activity relaunch on devices running Android 10 or lower
- [GOVUKAPP-2466](https://govukverify.atlassian.net/browse/GOVUKAPP-2466)
[GOVUKAPP-2466]: https://govukverify.atlassian.net/browse/GOVUKAPP-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-2466 Deep link with URL bug

---

design/src/main/kotlin/uk/gov/govuk/design/ui/component/Card.kt
design/src/main/kotlin/uk/gov/govuk/design/ui/theme/Color.kt

- Add new non tappable card
*Card is currently not used anywhere in the app
- [GOVUKAPP-2504](https://govukverify.atlassian.net/browse/GOVUKAPP-2504)
- [Figma board](https://www.figma.com/design/x5i4a5RT0xMhJAcjoIxefb/2025-06-GOV.UK-app-library-v2--UX-refresh?node-id=6532-6646&t=PgWWJCWJtE6mN0ua-0)
[GOVUKAPP-2504]: https://govukverify.atlassian.net/browse/GOVUKAPP-2504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GOVUKAPP-2504 Non tappable card

---

feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/Answer.kt
feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/ChatEntry.kt
feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/ChatInput.kt
feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/Markdown.kt
feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/Sources.kt

- Answer formatting: Remove bullet point (unordered) and number list (ordered) indentation
- Answer formatting: Spacing between the accuracy warning and the separator line inconsistent across OS versions
- Headlines: Revise headlines hierarchy - font size on headings in LLM generated answers
- Answer formatting: Answer needs spacing between title and answer
- List items: Line height for list items is broken
- Responses: Response typography / formatting
- Responses: Response title
- Detail of the expected outcome (some are duplicates of above items):
- There should be additional spacing padding between each bulleted item. (likely 10px)
- Any large headings should be the same size as regular text but bold
- Reduce indent on bullet points
- Reduce indent on numbered list
- Could we align …

GOVUKAPP-2528 : Markdown rendering investigation

---

feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/ChatInput.kt

- Use regular font size, weight, family and line height for character count text
- Use `primary` font colour - unless over limit - for character count text
- Don't use bold font weight when over limit - for character count text
- Use height of 32px for character count container
- Left align start of character count text inline with input text and answer text
- [GOVUKAPP-2486](https://govukverify.atlassian.net/browse/GOVUKAPP-2486)
| Within limit | Show count alignment | Over limit |
| --- | --- | --- |
| <img width="1080" height="2424" alt="Screenshot_20250926_113101" src="https://github.com/user-attachments/assets/8ac95d77-644a-49c5-90c7-8a7da4628c67" /> | <img width="1080" height="2424" alt="Screenshot_20250926_113119" src="https://github.com/user-attachments/assets/da5607e4-c6f2-4406-8a …

GOVUKAPP-2486 : Post amigo fixups
