.github/workflows/lint.yml, .github/workflows/pull_request.yml, .github/workflows/sonar_scanner.yml, .github/workflows/unit_test.yml, app/build.gradle.kts
Wasn't quite working as previously configured.
[JIRA GOVAPP-454](https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405/backlog?selectedIssue=GOVAPP-454)
=> Fix Sonar scanning

feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt
Onboarding pager swipe behaviour
- [GOVUKAPP-526](https://govukverify.atlassian.net/browse/GOVUKAPP-526)
[GOVUKAPP-526]: https://govukverify.atlassian.net/browse/GOVUKAPP-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-526: Onboarding pager swipe behaviour

feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt, feature/onboarding/src/main/res/values/strings.xml
GOVUKAPP-527: Page indicators
- [GOVUKAPP-527](https://govukverify.atlassian.net/browse/GOVUKAPP-527)
[GOVUKAPP-527]: https://govukverify.atlassian.net/browse/GOVUKAPP-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-527: Page indicators

.github/workflows/instrumented_test.yml, .github/workflows/lint.yml, .github/workflows/pull_request.yml, .github/workflows/sonar_scanner.yml, .github/workflows/unit_test.yml, .gitignore, app/build.gradle.kts, app/src/debug/google-services.json, app/src/main/kotlin/uk/govuk/app/di/AppModule.kt, build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
…ndancies
GOVUK-484: Add DI analytics
- [GOVUKAPP-484](https://govukverify.atlassian.net/browse/GOVUKAPP-484)
[GOVUKAPP-484]: https://govukverify.atlassian.net/browse/GOVUKAPP-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUK-484: Add DI analytics

app/src/main/AndroidManifest.xml, app/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt, app/src/main/kotlin/uk/govuk/app/di/AppModule.kt, app/src/test/kotlin/uk/govuk/app/analytics/AnalyticsClientTest.kt, feature/onboarding/build.gradle.kts, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/OnboardingPage.kt, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/OnboardingViewModel.kt, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/analytics/OnboardingAnalytics.kt, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt, feature/onboarding/src/test/kotlin/uk/govuk/app/onboarding/OnboardingViewModelTest.kt
Add Google analytics for onboarding flow
- [GOVUKAPP-511](https://govukverify.atlassian.net/browse/GOVUKAPP-511)
[GOVUKAPP-511]: https://govukverify.atlassian.net/browse/GOVUKAPP-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-511: GA onboarding

analytics/build.gradle.kts, design/build.gradle.kts, feature/home/build.gradle.kts, feature/onboarding/build.gradle.kts, feature/settings/build.gradle.kts
Add min sdk version to module build files to fix dex issue
=> Dex build fix

design/src/main/kotlin/uk/govuk/app/design/ui/theme/Type.kt, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt
- [GOVAPP-561](https://govukverify.atlassian.net/browse/GOVUKAPP-561)
- [Figma board](https://www.figma.com/design/JrYICS31qcr0jcwQUvNaNI/Android-Font-Library?node-id=18-352&t=gkoKlLZEwpCXwgf3-0)
=> GOVUKAPP 561 font library

design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt
I've included everything in the Figma and kept the existing names. So, nothing needs to be renamed - at the moment.
- [GOVAPP-562](https://govukverify.atlassian.net/browse/GOVUKAPP-562)
- [Figma board](https://www.figma.com/design/siD3CH5hRhIAmVTQ10xkjb/GOV.UK-app-library?node-id=668-2556&t=wCSYMH3H9KsZnnUr-0)
=> GOVUKAPP-562 Update Colour Palette

app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt
- [GOVAPP-563](https://govukverify.atlassian.net/browse/GOVUKAPP-563)
- [Figma board](https://www.figma.com/design/siD3CH5hRhIAmVTQ10xkjb/GOV.UK-app-library?node-id=0-1&t=QvDqgsl96e0VV5qc-0)
=> GOVUKAPP-563 Create Tokens Library

app/src/main/res/values-night/colors.xml, app/src/main/res/values/themes.xml
Set window and status bar colour during app launch preview for a slicker UX
=> App Launch Preview

app/src/main/kotlin/uk/govuk/app/MainActivity.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, feature/home/src/main/kotlin/uk/govuk/app/home/ui/HomeScreen.kt, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt
Fixes for issues related to edge to edge
- [GOVUKAPP-597](https://govukverify.atlassian.net/browse/GOVUKAPP-597)
[GOVUKAPP-597]: https://govukverify.atlassian.net/browse/GOVUKAPP-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-597: Edge to edge issues

design/src/main/kotlin/uk/govuk/app/design/ui/component/Label.kt, feature/home/src/main/kotlin/uk/govuk/app/home/ui/HomeScreen.kt, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt
- [GOVAPP-559](https://govukverify.atlassian.net/browse/GOVUKAPP-559)
- [Figma board](https://www.figma.com/design/siD3CH5hRhIAmVTQ10xkjb/GOV.UK-app-library?node-id=1064-3210&t=gz1zTiHlUuovczXc-0)
=> GOVUKAPP-559 Create label component

design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/TextField.kt, feature/search/build.gradle.kts, feature/search/src/main/kotlin/uk/govuk/app/search/navigation/SearchNavigation.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt, gradle/libs.versions.toml
Launch browser with search query
- [GOVUKAPP-657](https://govukverify.atlassian.net/browse/GOVUKAPP-657)
[GOVUKAPP-657]: https://govukverify.atlassian.net/browse/GOVUKAPP-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-657: Perform search

design/src/main/kotlin/uk/govuk/app/design/ui/component/Card.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/TextField.kt, design/src/main/res/values/strings.xml
- [GOVAPP-658](https://govukverify.atlassian.net/browse/GOVUKAPP-658)
=> GOVUKAPP-658 Accessibility

feature/home/src/main/kotlin/uk/govuk/app/home/ui/HomeScreen.kt, feature/home/src/main/res/values/strings.xml
- [GOVAPP-669](https://govukverify.atlassian.net/browse/GOVUKAPP-669)
=> GOVUKAPP-669 Add alt text to Homepage logo

app/src/main/kotlin/uk/govuk/app/ui/SplashScreen.kt, app/src/main/res/values/strings.xml, feature/home/src/main/res/values/strings.xml
=> Change . to the word dot for alt text

.github/workflows/merge_develop.yml, .github/workflows/pull_request.yml, app/build.gradle.kts, app/src/alpha/google-services.json, build.gradle.kts, gradle/libs.versions.toml
Distribute builds via Firebase App Distribution on merge into develop
- [GOVUKAPP-666](https://govukverify.atlassian.net/browse/GOVUKAPP-666)
[GOVUKAPP-666]: https://govukverify.atlassian.net/browse/GOVUKAPP-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-666: Distribute builds

analytics/build.gradle.kts, analytics/src/main/kotlin/uk/govuk/app/analytics/Analytics.kt, analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt, analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsDataStore.kt, analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsRepo.kt, analytics/src/test/java/uk/govuk/app/analytics/AnalyticsClientTest.kt, analytics/src/test/java/uk/govuk/app/analytics/AnalyticsDataStoreTest.kt, analytics/src/test/java/uk/govuk/app/analytics/AnalyticsRepoTest.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/Switch.kt, feature/settings/build.gradle.kts, feature/settings/src/main/kotlin/uk/govuk/app/settings/SettingsViewModel.kt, feature/settings/src/main/kotlin/uk/govuk/app/settings/ui/SettingsScreen.kt, feature/settings/src/test/kotlin/uk/govuk/app/settings/SettingsViewModelTest.kt
Enable/disable analytics based on toggle in settings
- [GOVUKAPP-708](https://govukverify.atlassian.net/browse/GOVUKAPP-708)
[GOVUKAPP-708]: https://govukverify.atlassian.net/browse/GOVUKAPP-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-708: Analytics toggle

analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt, analytics/src/main/kotlin/uk/govuk/app/analytics/extension/StringExtension.kt, analytics/src/test/java/uk/govuk/app/analytics/AnalyticsClientTest.kt, app/src/test/kotlin/uk/govuk/app/analytics/extension/StringExtensionTest.kt
Redact postcode, email address and NI number from search analytics
- [GOVUKAPP-695](https://govukverify.atlassian.net/browse/GOVUKAPP-695)
[GOVUKAPP-695]: https://govukverify.atlassian.net/browse/GOVUKAPP-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-695: Analytics PII

app/src/main/kotlin/uk/govuk/app/Constants.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, feature/search/build.gradle.kts, feature/search/src/main/kotlin/uk/govuk/app/search/navigation/SearchNavigation.kt, feature/settings/src/main/kotlin/uk/govuk/app/settings/navigation/SettingsNavigation.kt, feature/settings/src/main/kotlin/uk/govuk/app/settings/ui/SettingsScreen.kt, gradle/libs.versions.toml
Open privacy policy in browser
- [GOVUKAPP-718](https://govukverify.atlassian.net/browse/GOVUKAPP-718)
[GOVUKAPP-718]: https://govukverify.atlassian.net/browse/GOVUKAPP-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-718: Open privacy policy in browser

app/src/main/kotlin/uk/govuk/app/AppViewModel.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, app/src/test/kotlin/uk/govuk/app/AppViewModelTest.kt, config/src/main/kotlin/uk/govuk/app/config/data/remote/model/ReleaseFlags.kt, config/src/main/kotlin/uk/govuk/app/config/di/ConfigModule.kt, config/src/main/kotlin/uk/govuk/app/config/flags/DebugFlags.kt, config/src/main/kotlin/uk/govuk/app/config/flags/FlagRepo.kt, config/src/test/kotlin/uk/govuk/app/config/FlagRepoTest.kt
Add feature flag for topics
- [GOVUKAPP-770](https://govukverify.atlassian.net/browse/GOVUKAPP-770)
[GOVUKAPP-770]: https://govukverify.atlassian.net/browse/GOVUKAPP-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-770: Topics feature flag

config/build.gradle.kts, config/src/main/kotlin/uk/govuk/app/config/data/remote/model/Config.kt, config/src/main/kotlin/uk/govuk/app/config/di/ConfigModule.kt, feature/topics/build.gradle.kts, feature/topics/src/main/kotlin/uk/govuk/app/topics/di/TopicsModule.kt
Tidy up todos
- [GOVUKAPP-779](https://govukverify.atlassian.net/browse/GOVUKAPP-779)
[GOVUKAPP-779]: https://govukverify.atlassian.net/browse/GOVUKAPP-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-779: Tidy up todo items

config/build.gradle.kts, config/src/main/kotlin/uk/govuk/app/config/ConfigRepo.kt, config/src/main/kotlin/uk/govuk/app/config/SignatureValidator.kt, config/src/main/kotlin/uk/govuk/app/config/data/remote/ConfigApi.kt, config/src/main/kotlin/uk/govuk/app/config/data/remote/model/ConfigResponse.kt, config/src/main/kotlin/uk/govuk/app/config/di/ConfigModule.kt, config/src/test/kotlin/uk/govuk/app/config/ConfigRepoTest.kt, config/src/test/kotlin/uk/govuk/app/config/SignatureValidatorTest.kt, gradle/libs.versions.toml
Implement a mechanism within the mobile app to verify the signature of the configuration data using the bundled public key.
- [GOVAPP-586](https://govukverify.atlassian.net/browse/GOVUKAPP-586)
=> GOVUKAPP-586 verify config signature

design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/TextField.kt, feature/search/src/main/kotlin/uk/govuk/app/search/SearchViewModel.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt
When the `Clear` button/icon is pressed, both the search input field and the search results should be cleared.
- [GOVAPP-778](https://govukverify.atlassian.net/browse/GOVUKAPP-778)
=> GOVUKAPP-778 Clear search results

feature/topics/consumer-rules.pro
Update proguard rules for topics
=> Update proguard rules for topics

app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicsViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/EditTopicsScreen.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/widget/TopicsWidget.kt, feature/topics/src/main/res/values/strings.xml, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicsViewModelTest.kt
Edit topics click and screen view analytics
- [GOVUKAPP-792](https://govukverify.atlassian.net/browse/GOVUKAPP-792)
[GOVUKAPP-792]: https://govukverify.atlassian.net/browse/GOVUKAPP-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Edit topics click and screen view analytics

analytics/src/main/kotlin/uk/govuk/app/analytics/Analytics.kt, analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt, analytics/src/test/kotlin/uk/govuk/app/analytics/AnalyticsClientTest.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicsViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/EditTopicsScreen.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicsViewModelTest.kt
Function analytics for topics toggle
- [GOVUKAPP-765](https://govukverify.atlassian.net/browse/GOVUKAPP-765)
[GOVUKAPP-765]: https://govukverify.atlassian.net/browse/GOVUKAPP-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Function analytics for topics toggle

feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/extension/RemoteTopic.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/navigation/TopicsNavigation.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicScreen.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/model/TopicUi.kt, feature/topics/src/main/res/values/strings.xml, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/extension/RemoteTopicTest.kt
Subtopic pages - dynamic title for subtopics section based on if it is a subtopic and contains content 
- [GOVUKAPP-847](https://govukverify.atlassian.net/browse/GOVUKAPP-847)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=338-13767&t=sKRUGdHq7xAKqLA0-4)
[GOVUKAPP-847]: https://govukverify.atlassian.net/browse/GOVUKAPP-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-847: Subtopic pages

feature/topics/src/main/kotlin/uk/govuk/app/topics/AllStepByStepsViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/extension/RemoteTopic.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/extension/TopicItem.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/navigation/TopicsNavigation.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/AllStepByStepsScreen.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/AllStepByStepsViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/data/TopicsRepoTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/extension/RemoteTopicTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/extension/TopicItemTest.kt
All step by steps screen
- [GOVUKAPP-812](https://govukverify.atlassian.net/browse/GOVUKAPP-812)
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-apps-and-notifications?node-id=16521-4374&t=3AB2AZ0Vuz4iocuV-4)
[GOVUKAPP-812]: https://govukverify.atlassian.net/browse/GOVUKAPP-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-812: All step by steps screen

design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicScreen.kt
Handle long topic titles that wrap over multiple lines
- [GOVUKAPP-875](https://govukverify.atlassian.net/browse/GOVUKAPP-875)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=2308-12288&node-type=frame&t=YpR43mMaUmIahsI6-0)
[GOVUKAPP-875]: https://govukverify.atlassian.net/browse/GOVUKAPP-875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-875: Long topic titles

design/src/main/kotlin/uk/govuk/app/design/ui/component/Card.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/component/Card.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/component/Header.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/component/TextField.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/widget/SearchWidget.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/AllTopicsScreen.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/component/Card.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/widget/TopicsWidget.kt
Move feature specific UI components into corresponding feature modules
=> Design module tidy up

app/src/main/kotlin/uk/govuk/app/AppViewModel.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, app/src/test/kotlin/uk/govuk/app/AppViewModelTest.kt, config/src/main/kotlin/uk/govuk/app/config/data/flags/DebugFlags.kt, config/src/main/kotlin/uk/govuk/app/config/data/flags/FlagRepo.kt, config/src/main/kotlin/uk/govuk/app/config/data/remote/model/ReleaseFlags.kt, config/src/test/kotlin/uk/govuk/app/config/data/flags/FlagRepoTest.kt
Feature Flag for Pages You've Visited
Add feature flag and logic for showing visited items home screen widget
- [GOVAPP-776](https://govukverify.atlassian.net/browse/GOVUKAPP-776)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-83650&node-type=canvas&t=cpDf2GEviDDFe9YA-0)
=> GOVUKAPP-776 Feature Flag for Pages You've Visited

design/src/main/kotlin/uk/govuk/app/design/ui/component/List.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt
- [GOVAPP-650](https://govukverify.atlassian.net/browse/GOVUKAPP-650)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-83650&node-type=canvas&t=boWhb5v21KBDhGbi-0)
|---|---|
| ![Screenshot_20241105_160055](https://github.com/user-attachments/assets/f3d5be07-bb71-499e-b05a-7e73c721b406) | ![Screenshot_20241105_160148](https://github.com/user-attachments/assets/1d25918f-1406-4ddc-b5c5-c537e2b9d04f) |
=> Create list item

feature/search/src/test/kotlin/uk/govuk/app/search/SearchViewModelTest.kt, feature/topics/build.gradle.kts, feature/topics/src/main/kotlin/uk/govuk/app/topics/AllStepByStepsViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicViewModel.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/AllStepByStepsViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicViewModelTest.kt
- [GOVAPP-840](https://govukverify.atlassian.net/browse/GOVUKAPP-840)
=> Display topic interactions in pages you've visited

app/src/main/kotlin/uk/govuk/app/navigation/AppLaunchNavigation.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, app/src/test/kotlin/uk/govuk/app/navigation/AppLaunchNavigationTest.kt
Use remember to ensure only a single instance of app launch nav is created
- [GOVUKAPP-913](https://govukverify.atlassian.net/browse/GOVUKAPP-913)
[GOVUKAPP-913]: https://govukverify.atlassian.net/browse/GOVUKAPP-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-913: Topic selection bug

gradle.properties
Reverts alphagov/govuk-mobile-android-app#112
=> Re-instate "Set Gradle configuration-cache"

feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicSelectionScreen.kt, feature/topics/src/main/res/values/strings.xml
Announce selection/deselection of topic for talkback
- [GOVUKAPP-804](https://govukverify.atlassian.net/browse/GOVUKAPP-804)
[GOVUKAPP-804]: https://govukverify.atlassian.net/browse/GOVUKAPP-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-804: Topic selection during onboarding

app/src/main/kotlin/uk/govuk/app/AppViewModel.kt, app/src/main/kotlin/uk/govuk/app/navigation/AppLaunchNavigation.kt, app/src/main/kotlin/uk/govuk/app/ui/ForcedUpdateScreen.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, app/src/main/res/values/strings.xml, app/src/test/kotlin/uk/govuk/app/AppViewModelTest.kt, app/src/test/kotlin/uk/govuk/app/navigation/AppLaunchNavigationTest.kt, config/src/main/kotlin/uk/govuk/app/config/data/flags/DebugFlags.kt, config/src/main/kotlin/uk/govuk/app/config/data/flags/FlagRepo.kt, config/src/test/kotlin/uk/govuk/app/config/data/flags/FlagRepoTest.kt
Forced Update
Add forced update screen and logic to show it
- [GOVAPP-592](https://govukverify.atlassian.net/browse/GOVUKAPP-592)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=363-6730&node-type=section&t=ufGd6456NYfQNmqg-0)
|---|---|
| ![Screenshot_1731513384](https://github.com/user-attachments/assets/8288720e-058f-4185-b9bd-c4b0c3738047) | ![Screenshot_1731513355](https://github.com/user-attachments/assets/696331f1-b8cf-4fbb-86b5-83003c5382b4) |
=> GOVUKAPP-592 Forced Update

app/src/main/kotlin/uk/govuk/app/AppUiState.kt, app/src/main/kotlin/uk/govuk/app/AppViewModel.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, app/src/test/kotlin/uk/govuk/app/AppViewModelTest.kt, app/src/test/kotlin/uk/govuk/app/navigation/AppLaunchNavigationTest.kt, config/src/main/kotlin/uk/govuk/app/config/data/ConfigExceptions.kt, config/src/main/kotlin/uk/govuk/app/config/data/ConfigRepo.kt, config/src/test/kotlin/uk/govuk/app/config/data/ConfigRepoTest.kt
User messaging for unverified config signature
- Show forced update screen when app config signature is invalid on app launch.
- Align with iOS that any other app config errors result in app unavailable screen being shown on app launch.
- [GOVAPP-781](https://govukverify.atlassian.net/browse/GOVUKAPP-781)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=363-6730&node-type=section&t=3iXvvIdHgGeXyKG4-0)
=> GOVUKAPP-781 User messaging for unverified config signature

feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicScreen.kt
Add box around content to prevent content from expanding
- [GOVUKAPP-953](https://govukverify.atlassian.net/browse/GOVUKAPP-953)
[GOVUKAPP-953]: https://govukverify.atlassian.net/browse/GOVUKAPP-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-953: Topic page transition bug

feature/topics/src/main/kotlin/uk/govuk/app/topics/EditTopicsViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicSelectionViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicsWidgetViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/data/TopicsRepo.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/data/local/TopicsDataStore.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/data/local/TopicsLocalDataSource.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicSelectionScreen.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/widget/TopicsWidget.kt, feature/topics/src/main/res/values/strings.xml, feature/topics/src/test/kotlin/uk/govuk/app/topics/EditTopicsViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicSelectionViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicsWidgetViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/data/TopicsRepoTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/data/local/TopicsDataStoreTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/data/local/TopicsLocalDataSourceTest.kt
Dynamic header text based on customisation
- [GOVUKAPP-939](https://govukverify.atlassian.net/browse/GOVUKAPP-939)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=303-2915&t=YzKBhSIMwNlTSbx3-4)
[GOVUKAPP-939]: https://govukverify.atlassian.net/browse/GOVUKAPP-939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-939: Topic widget dynamic header text

feature/settings/build.gradle.kts
- [GOVAPP-795](https://govukverify.atlassian.net/browse/GOVUKAPP-795)
=> GOVUKAPP-795 Update the Help and Feedback URL in the Settings screen

design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/VisitedViewModel.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/data/store/VisitedLocalDataSource.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/model/VisitedUi.kt, feature/visited/src/main/res/values/strings.xml, feature/visited/src/test/kotlin/uk/govuk/app/visited/VisitedViewModelTest.kt, feature/visited/src/test/kotlin/uk/govuk/app/visited/data/store/VisitedLocalDataSourceTest.kt
Addresses the following functionality:
- Removing visited items from the Realm database
- Selecting and deselecting all visited items
- Removing all selected visited items
- The `Select all` and `Remove` button logic
- Colour for disabled `Remove` button based on discussion with Design (ER)
- Analytics requirements added based on discussion with Data Analyst (AB)
- [GOVAPP-652](https://govukverify.atlassian.net/browse/GOVUKAPP-652)
```bash
Logging event: origin=app,name=screen_view(_vs),params=Bundle[{language=en, screen_title=Pages you've visited, ga_event_origin(_o)=app, engagement_time_msec(_et)=42618, ga_previous_class(_pc)=EditVisitedScreen, ga_previous_id(_pi)=8075437394341788312, ga_previous_screen(_pn)=Pages you've visited, ga_screen_class(_sc)=VisitedScreen, …
```
=> Visited Items : edit storage

app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, feature/settings/src/main/kotlin/uk/govuk/app/settings/navigation/SettingsNavigation.kt
Add device info to help url
- [GOVUKAPP-992](https://govukverify.atlassian.net/browse/GOVUKAPP-992)
[GOVUKAPP-992]: https://govukverify.atlassian.net/browse/GOVUKAPP-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-992: Add device info to help url

feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt
=> Previous fix broke month section padding

feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt
Allow select/deselect all button to wrap to prevent remove button text wrapping and truncation
- [GOVUKAPP-1013](https://govukverify.atlassian.net/browse/GOVUKAPP-1013)
[GOVUKAPP-1013]: https://govukverify.atlassian.net/browse/GOVUKAPP-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1013: PYV Remove Button Bug

analytics/src/main/kotlin/uk/govuk/app/analytics/ui/AnalyticsConsentScreen.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/Label.kt, design/src/main/kotlin/uk/govuk/app/design/ui/component/List.kt, feature/home/src/main/kotlin/uk/govuk/app/home/ui/HomeScreen.kt, feature/onboarding/src/main/kotlin/uk/govuk/app/onboarding/ui/OnboardingScreen.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicScreen.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicSelectionScreen.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/widget/TopicsWidget.kt
Add heading semantic to ui elements listed as headings for talkback
- [GOVAPP-1027](https://govukverify.atlassian.net/browse/GOVUKAPP-1027)
https://github.com/user-attachments/assets/de14b766-a6ce-4b05-adbe-f14030b1ce2b
=> GOVUKAPP-1027 Header labelling

feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt, feature/search/src/main/res/values/strings.xml
Add header to search results and focus on it when search results are displayed
- [GOVUKAPP-1029](https://govukverify.atlassian.net/browse/GOVUKAPP-1029)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=3600-27558&t=KNLJY4udtFS7ebEx-4)
[Screen_recording_20241217_145145.webm](https://github.com/user-attachments/assets/64e3364b-e61e-4ac2-9101-6fa620e2d27c)
[GOVUKAPP-1029]: https://govukverify.atlassian.net/browse/GOVUKAPP-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1029: Search results header

feature/settings/src/main/kotlin/uk/govuk/app/settings/ui/FeedbackPromptWidget.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/widget/TopicsWidget.kt, feature/topics/src/main/res/values/strings.xml
Display message when user deselects all topics
- [GOVUKAPP-1037](https://govukverify.atlassian.net/browse/GOVUKAPP-1037)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=3829-27828&t=9W4LVkpEg8JYqImY-4)
[GOVUKAPP-1037]: https://govukverify.atlassian.net/browse/GOVUKAPP-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1037: User removes all topics

feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicSelectionViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/data/TopicsRepo.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/data/local/TopicsLocalDataSource.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicSelectionViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/data/TopicsRepoTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/data/local/TopicsLocalDataSourceTest.kt
Fix for topic selection bug during onboarding
- [GOVUKAPP-1056](https://govukverify.atlassian.net/browse/GOVUKAPP-1056)
[GOVUKAPP-1056]: https://govukverify.atlassian.net/browse/GOVUKAPP-1056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1056: Topic selection bug

app/src/main/res/values/strings.xml
Correct typo in full screen offline message
- [GOVUKAPP-1041](https://govukverify.atlassian.net/browse/GOVUKAPP-1041)
[GOVUKAPP-1041]: https://govukverify.atlassian.net/browse/GOVUKAPP-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1041: Correct typo in full screen offline message

design/src/main/kotlin/uk/govuk/app/design/ui/component/Error.kt, feature/search/src/main/kotlin/uk/govuk/app/search/SearchUiState.kt, feature/search/src/main/kotlin/uk/govuk/app/search/SearchViewModel.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/SearchScreen.kt, feature/search/src/test/kotlin/uk/govuk/app/search/SearchViewModelTest.kt, networking/src/main/kotlin/uk/govuk/app/networking/ui/component/OfflineMessage.kt, networking/src/main/kotlin/uk/govuk/app/networking/ui/component/ProblemMessage.kt
Request focus on search error messages
- [GOVUKAPP-1051](https://govukverify.atlassian.net/browse/GOVUKAPP-1051)
[GOVUKAPP-1051]: https://govukverify.atlassian.net/browse/GOVUKAPP-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1051: Search error message focus

design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/widget/TopicsWidget.kt, feature/topics/src/main/res/values/strings.xml, feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt, feature/visited/src/main/res/values/strings.xml
Add alt-text to edit and done buttons
- [GOVAPP-1025](https://govukverify.atlassian.net/browse/GOVUKAPP-1025)
=> GOVUKAPP-1025: Edit button context

design/src/main/kotlin/uk/govuk/app/design/ui/component/Header.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/VisitedScreen.kt, feature/visited/src/main/res/values/strings.xml
Move 'back button' alt text to 'done button'
- [GOVAPP-1025](https://govukverify.atlassian.net/browse/GOVUKAPP-1025)
https://github.com/user-attachments/assets/6355093e-ac02-4092-b481-2b99b1074fdf
=> GOVUKAPP-1025 Edit button context - update

.github/workflows/merge_develop.yml, app/build.gradle.kts
Sign alpha build
- [GOVUKAPP-1085](https://govukverify.atlassian.net/browse/GOVUKAPP-1085)
[GOVUKAPP-1085]: https://govukverify.atlassian.net/browse/GOVUKAPP-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1085: Sign alpha build

feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt, feature/visited/src/main/res/values/strings.xml
- [GOVAPP-1083](https://govukverify.atlassian.net/browse/GOVUKAPP-1083)
- N/A
|---|---|
| ![before](https://github.com/user-attachments/assets/3bacc471-a575-47b2-9707-d21ebfe273a0) | ![after](https://github.com/user-attachments/assets/1bb43124-0814-48f9-a087-e34e334677b0) |
=> GOVUKAPP-1083: Change `Done` button to `Cancel`

analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt, analytics/src/test/kotlin/uk/govuk/app/analytics/AnalyticsClientTest.kt, app/src/main/kotlin/uk/govuk/app/AppViewModel.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, app/src/main/res/values/strings.xml, app/src/test/kotlin/uk/govuk/app/AppViewModelTest.kt
Add extra required params to FA widget navigation event
Params:
- External (true/false)
- Section ("Homepage")
- [GOVAPP-1079](https://govukverify.atlassian.net/browse/GOVUKAPP-1079)
https://github.com/user-attachments/assets/e72c3959-08c8-4c4b-8542-bd6e2bff9994
=> GOVUKAPP-1079 Homepage feedback card stat

feature/topics/src/main/kotlin/uk/govuk/app/topics/AllStepByStepsViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/data/TopicsRepo.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/extension/RemoteTopic.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/navigation/TopicsNavigation.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/AllStepByStepsViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/data/TopicsRepoTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/extension/RemoteTopicTest.kt
Cache step by steps when fetching topic
- [GOVUKAPP-1114](https://govukverify.atlassian.net/browse/GOVUKAPP-1114)
[GOVUKAPP-1114]: https://govukverify.atlassian.net/browse/GOVUKAPP-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1114: Step by steps API call

app/src/main/kotlin/uk/govuk/app/MainActivity.kt, app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, feature/home/src/main/kotlin/uk/govuk/app/home/navigation/HomeNavigation.kt, feature/settings/src/main/kotlin/uk/govuk/app/settings/navigation/SettingsNavigation.kt
Remove compose nav deeplink handling and add placeholder for manually handling them
- [GOVUKAPP-1120](https://govukverify.atlassian.net/browse/GOVUKAPP-1120)
[GOVUKAPP-1120]: https://govukverify.atlassian.net/browse/GOVUKAPP-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1120: Deeplinks

design/src/main/kotlin/uk/govuk/app/design/ui/component/Label.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/component/Grid.kt
Calculate column count based on screen width and font scale, hypehnate labels
- [GOVUKAPP-971](https://govukverify.atlassian.net/browse/GOVUKAPP-971)
[GOVUKAPP-971]: https://govukverify.atlassian.net/browse/GOVUKAPP-971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-971: Topics breakpoints

analytics/src/main/kotlin/uk/govuk/app/analytics/AnalyticsClient.kt, analytics/src/main/kotlin/uk/govuk/app/analytics/FirebaseAnalyticsClient.kt, analytics/src/main/kotlin/uk/govuk/app/analytics/data/local/model/EcommerceEvent.kt, analytics/src/test/kotlin/uk/govuk/app/analytics/AnalyticsClientTest.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/AllStepByStepsViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/AllStepByStepsScreen.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/TopicScreen.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/AllStepByStepsViewModelTest.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicViewModelTest.kt
Follows the guidelines laid out here:
- [Firebase reference](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Param?_gl=1*17ayxwe*_up*MQ..*_ga*MjA3MTIwMTg5Ny4xNzM5Mjc1MjQ4*_ga_CW55HF8NVT*MTczOTI3NTI0Ny4xLjAuMTczOTI3NTYzNS4wLjAuMA..)
- [GTAG Reference](https://developers.google.com/tag-platform/gtagjs/reference/events)
- [Select an item from a list](https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag#select_an_item_from_a_list)
- [For online sales](https://support.google.com/analytics/answer/9267735?sjid=11948565095048522053-EU#online-sales)
⚠️ At the request of the Performance Analysis team, none of the pre-existing events have been altered or removed.
- …
=> GOVUKAPP-1143: Add ecommerce event for Topics

app/src/main/kotlin/uk/govuk/app/ui/GovUkApp.kt, app/src/main/kotlin/uk/govuk/app/ui/SplashScreen.kt, design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt
Update splash screen to use primary blue in dark mode
- [GOVUKAPP-1194](https://govukverify.atlassian.net/browse/GOVUKAPP-1194)
[GOVUKAPP-1194]: https://govukverify.atlassian.net/browse/GOVUKAPP-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1194: Splash screen dark mode

design/src/main/kotlin/uk/govuk/app/design/ui/component/Button.kt, design/src/main/kotlin/uk/govuk/app/design/ui/theme/Color.kt, feature/search/src/main/kotlin/uk/govuk/app/search/ui/PreviousSearches.kt, feature/visited/src/main/kotlin/uk/govuk/app/visited/ui/EditVisitedScreen.kt
- [GOVUKAPP-1206](https://govukverify.atlassian.net/browse/GOVUKAPP-1206)
- [Figma](https://www.figma.com/design/siD3CH5hRhIAmVTQ10xkjb/GOV.UK-app-library-BETA?node-id=0-1&p=f&t=sgjv36wuiTHfNiim-0)
- [Wrap up doc](https://docs.google.com/document/d/1s2iJ3oWzBttwTVLTTDJeJrvtpTrFm23C9F0otN2iikA/edit?tab=t.0#bookmark=id.obdx7blwfskx)
|---|---|
| ![before-topics-light](https://github.com/user-attachments/assets/9c1d3e24-7145-4059-92ab-4fa7443ea87d) | ![after-topics-light](https://github.com/user-attachments/assets/8979ef4a-b3a8-4b7e-9198-b5ef6a534898) |
| ![before-topics-dark](https://github.com/user-attachments/assets/78312f6a-d67f-4a9e-9f5b-8e53a7eb51e8) | ![after-topics-dark](https://github.com/user-attachments/assets/dce0a509-b317-4a2d-afdd-110d728db4a1) |
| Before | …
=> GOVUKAPP-1206: branding wrap up

.github/pull_request_template.md
Update to JIRA ticket convention and change the screenshot section
=> Update the default PR message

feature/topics/src/main/kotlin/uk/govuk/app/topics/TopicsWidgetViewModel.kt, feature/topics/src/main/kotlin/uk/govuk/app/topics/ui/widget/TopicsWidget.kt, feature/topics/src/test/kotlin/uk/govuk/app/topics/TopicsWidgetViewModelTest.kt
- [GOVAPP-1149](https://govukverify.atlassian.net/browse/GOVUKAPP-1149)
```shell
name=view_item_list,
params=Bundle[
{
item_list_name=HomeScreen,
item_list_id=Homepage,
items=[
Bundle[
{
item_name=Benefits,
index=1,
item_category=Topics,
location_id=benefits
}
], Bundle[
{
item_name=Driving and transport,
index=2,
item_category=Topics,
location_id=driving-transport
}
]
],
results=2
}
]
```
```shell
name=select_item,
params=Bundle[
{
item_list_name=HomeScreen,
item_list_id=Homepage,
items=[
Bundle[
{
item_name=Driving and transport,
index=2,
item_category=Topics,
location_id=driving-transport
}
]
],
results=1
}
]
```
```shell
name=view_item_list,
params=Bundle[
{
item_list_name=HomeScreen,
item_list_id=Homepage,
items=[],
results=0
}
]
```
=> GOVUKAPP-1149: Ecommerce events for homepage

app/src/main/kotlin/uk/govuk/app/AppViewModel.kt
- [GOVUKAPP-1221](https://govukverify.atlassian.net/browse/GOVUKAPP-1221)
[GOVUKAPP-1221]: https://govukverify.atlassian.net/browse/GOVUKAPP-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove feedback widget

app/src/main/kotlin/uk/govuk/app/ui/SplashScreen.kt
Reduce animation delay when animations are disabled
- [GOVUKAPP-1226](https://govukverify.atlassian.net/browse/GOVUKAPP-1226)
[GOVUKAPP-1226]: https://govukverify.atlassian.net/browse/GOVUKAPP-1226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1226: Splash Animation Disabled Delay

feature/home/build.gradle.kts, feature/home/src/main/kotlin/uk/govuk/app/home/HomeViewModel.kt, feature/home/src/main/kotlin/uk/govuk/app/home/ui/HomeScreen.kt, feature/home/src/test/kotlin/uk/govuk/app/home/HomeViewModelTest.kt
This is a spike into:
- Landscape logo removal 
- Search feature flag behaviour
⚠️  Please note that moving the search bar into the header is the subject of [GOVUKAPP-1249](https://govukverify.atlassian.net/browse/GOVUKAPP-1249) so the screen shots and video show it in it's current position.
- [GOVUKAPP-1247](https://govukverify.atlassian.net/browse/GOVUKAPP-1247)
- [GOVUKAPP-1252](https://govukverify.atlassian.net/browse/GOVUKAPP-1252)
- [Figma board](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-74994&p=f&t=8x0ObBZgwkSAbjbf-0)
| Flag on | Flag off |
| ![after-flag-on-portrait-light](https://github.com/user-attachments/assets/d01e3f8e-28b7-4acb-ae7d-19c1fca0a711) | …
=> GOVUKAPP-1247 & GOVUKAPP-1252

analytics/src/main/kotlin/uk/gov/govuk/analytics/AnalyticsClient.kt, analytics/src/test/kotlin/uk/gov/govuk/analytics/AnalyticsClientTest.kt, app/src/androidTest/kotlin/uk/gov/govuk/GovUKApplicationTest.kt, app/src/androidTest/kotlin/uk/gov/govuk/MainActivityTest.kt, app/src/main/AndroidManifest.xml, app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt, app/src/main/kotlin/uk/gov/govuk/MainActivity.kt, app/src/main/kotlin/uk/gov/govuk/extension/StringExtension.kt, app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt, app/src/main/res/values/strings.xml, app/src/test/kotlin/uk/gov/govuk/AppViewModelTest.kt, app/src/test/kotlin/uk/gov/govuk/extension/StringExtensionTest.kt, feature/home/src/main/kotlin/uk/gov/govuk/home/navigation/HomeNavigation.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/navigation/SearchNavigation.kt, feature/settings/src/main/kotlin/uk/gov/govuk/settings/navigation/SettingsNavigation.kt, feature/topics/src/main/kotlin/uk/gov/govuk/topics/navigation/TopicsNavigation.kt, feature/visited/src/main/kotlin/uk/gov/govuk/visited/navigation/VisitedNavigation.kt
- Show an alert dialog when the app receives a deeplink it doesn't have
- Add topic path deeplink (e.g "govuk://app/topics/benefits?isSubtopic=false”)
- Prevent deeplinking to a feature thats turned off by a feature flag (by not adding turned off feature navigation graphs to the nav host)
- Add the following required schemes and hosts for deeplinks: govuk://app.gov.uk, govuk://gov.uk, https://app.gov.uk
- [GOVUKAPP-1197](https://govukverify.atlassian.net/browse/GOVUKAPP-1197)
| ![Screenshot_1742918264](https://github.com/user-attachments/assets/194b9211-2bd9-4599-830d-10ebf4f02704) | ![Screenshot_1742919180](https://github.com/user-attachments/assets/f5ef51a1-5c30-403e-b108-11b76e829a81) |
[GOVUKAPP-1197]: …
=> GOVUKAPP-1197 Broken link graceful failure

feature/search/src/main/kotlin/uk/gov/govuk/search/SearchUiState.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/SearchViewModel.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/ui/SearchScreen.kt, feature/search/src/test/kotlin/uk/gov/govuk/search/SearchViewModelTest.kt
Bug fix - prevent suggested searches being display on top of search results
- [GOVUKAPP-1380](https://govukverify.atlassian.net/browse/GOVUKAPP-1380)
[GOVUKAPP-1380]: https://govukverify.atlassian.net/browse/GOVUKAPP-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1380: Suggested searches bug

feature/local/.gitignore, feature/local/src/main/kotlin/uk/govuk/app/local/data/LocalRepo.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/model/StoredLocalAuthority.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/store/LocalDataSource.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/store/LocalRealmProvider.kt, feature/local/src/test/kotlin/uk/govuk/app/local/data/LocalRepoTest.kt, feature/local/src/test/kotlin/uk/govuk/app/local/data/store/LocalDataSourceTest.kt
- [GOVUKAPP-1356](https://govukverify.atlassian.net/browse/GOVUKAPP-1356)
[GOVUKAPP-1356]: https://govukverify.atlassian.net/browse/GOVUKAPP-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1356: Store local authority

app/src/main/kotlin/uk/gov/govuk/navigation/AppLaunchNavigation.kt, app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt, app/src/test/kotlin/uk/gov/govuk/navigation/AppLaunchNavigationTest.kt, feature/topics/src/main/kotlin/uk/gov/govuk/topics/navigation/TopicsNavigation.kt
- Add a topic selection graph route to resolve the crash
- [GOVUKAPP-1525](https://govukverify.atlassian.net/browse/GOVUKAPP-1525)
[GOVUKAPP-1525]: https://govukverify.atlassian.net/browse/GOVUKAPP-1525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1525 Topic selection crash

data/build.gradle.kts, data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt, data/src/main/kotlin/uk/gov/govuk/data/auth/di/AuthModule.kt, data/src/test/kotlin/uk/gov/govuk/data/auth/AuthRepoTest.kt, login/src/main/kotlin/uk/gov/govuk/login/BiometricViewModel.kt, login/src/main/kotlin/uk/gov/govuk/login/LoginViewModel.kt, login/src/main/kotlin/uk/gov/govuk/login/navigation/LoginNavigation.kt, login/src/main/kotlin/uk/gov/govuk/login/ui/LoginScreen.kt, login/src/main/res/values/strings.xml, login/src/test/kotlin/uk/gov/govuk/login/LoginViewModelTest.kt
Re-entering the app as a signed in/out user
- [GOVUKAPP-1499](https://govukverify.atlassian.net/browse/GOVUKAPP-1499)
[GOVUKAPP-1499]: https://govukverify.atlassian.net/browse/GOVUKAPP-1499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1499: Re-entry

app/src/main/kotlin/uk/gov/govuk/AppUiState.kt, app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt, app/src/main/kotlin/uk/gov/govuk/navigation/AppLaunchNavigation.kt, config/src/main/kotlin/uk/gov/govuk/config/data/flags/FlagRepo.kt, config/src/main/kotlin/uk/gov/govuk/config/di/ConfigModule.kt, config/src/test/kotlin/uk/gov/govuk/config/data/flags/FlagRepoTest.kt
Add login local/dev only feature flag
=> Login feature flag

app/build.gradle.kts, app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt, app/src/main/kotlin/uk/gov/govuk/ui/HomeWidgets.kt
Introduce patch to version name
=> Introduce patch to version name

app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt, app/src/test/kotlin/uk/gov/govuk/AppViewModelTest.kt, feature/local/src/test/kotlin/uk/govuk/app/local/DefaultLocalFeatureTest.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/DefaultSearchFeature.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/SearchFeature.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/data/SearchRepo.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/data/local/SearchLocalDataSource.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/di/SearchModule.kt, feature/search/src/test/kotlin/uk/gov/govuk/search/DefaultSearchFeatureTest.kt, feature/search/src/test/kotlin/uk/gov/govuk/search/data/SearchRepoTest.kt, feature/search/src/test/kotlin/uk/gov/govuk/search/data/local/SearchLocalDataSourceTest.kt, feature/topics/src/main/kotlin/uk/gov/govuk/topics/di/TopicsModule.kt, feature/visited/src/main/kotlin/uk/gov/govuk/visited/Visited.kt, feature/visited/src/main/kotlin/uk/gov/govuk/visited/VisitedClient.kt, feature/visited/src/main/kotlin/uk/gov/govuk/visited/data/VisitedRepo.kt, feature/visited/src/main/kotlin/uk/gov/govuk/visited/data/store/VisitedLocalDataSource.kt, feature/visited/src/test/kotlin/uk/gov/govuk/visited/VisitedClientTest.kt, feature/visited/src/test/kotlin/uk/gov/govuk/visited/data/VisitedRepoTest.kt, feature/visited/src/test/kotlin/uk/gov/govuk/visited/data/store/VisitedLocalDataSourceTest.kt
Clear searches and visited items
- [GOVUKAPP-1521](https://govukverify.atlassian.net/browse/GOVUKAPP-1521)
[GOVUKAPP-1521]: https://govukverify.atlassian.net/browse/GOVUKAPP-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1521 - Re-entering the app (shared device)

feature/local/src/main/kotlin/uk/govuk/app/local/LocalViewModel.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/remote/LocalApiCall.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/remote/model/LocalAuthorityResult.kt, feature/local/src/main/res/values/strings.xml, feature/local/src/test/kotlin/uk/govuk/app/local/LocalViewModelTest.kt, feature/local/src/test/kotlin/uk/govuk/app/local/data/remote/LocalApiCallTest.kt
- [GOVUKAPP-1597](https://govukverify.atlassian.net/browse/GOVUKAPP-1597)
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-apps-and-notifications?node-id=23400-4822&t=nRp8J8UfCzlmzODb-4)
| ![before](https://github.com/user-attachments/assets/d12c596b-d55a-49f2-a29b-da40c01dbd24) | ![after](https://github.com/user-attachments/assets/16443008-399b-4d9d-9ca0-0506a4925810) |
| ![before-dark](https://github.com/user-attachments/assets/f71f41ca-2484-4da1-a7ff-f1de4f71168f) | ![after-dark](https://github.com/user-attachments/assets/9a4e22eb-3f4e-4884-8c36-5ef06b1ddb5f) |
[GOVUKAPP-1597]: https://govukverify.atlassian.net/browse/GOVUKAPP-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1597 : Show error message on 429 rate limiting HTTP status

feature/local/src/main/kotlin/uk/govuk/app/local/LocalViewModel.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/remote/LocalApiCall.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/remote/model/LocalAuthorityResult.kt, feature/local/src/main/res/values/strings.xml, feature/local/src/test/kotlin/uk/govuk/app/local/LocalViewModelTest.kt, feature/local/src/test/kotlin/uk/govuk/app/local/data/remote/LocalApiCallTest.kt
- [GOVUKAPP-1714](https://govukverify.atlassian.net/browse/GOVUKAPP-1714)
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-apps-and-notifications?node-id=23391-4159&t=NKnpBPrp17kyyt9x-0)
| Light | Dark |
| ![after](https://github.com/user-attachments/assets/56d4b37c-012a-499d-9785-7543a2848209) | ![after-dark](https://github.com/user-attachments/assets/4dc460e2-d59d-49aa-8f79-02b18c3bb34c) |
[GOVUKAPP-1714]: https://govukverify.atlassian.net/browse/GOVUKAPP-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1714 : Display not connected error when device is offline

config/src/main/kotlin/uk/gov/govuk/config/data/flags/FlagRepo.kt, data/build.gradle.kts, data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt, data/src/main/kotlin/uk/gov/govuk/data/auth/di/AuthModule.kt, data/src/main/kotlin/uk/gov/govuk/data/remote/AuthApi.kt, data/src/test/kotlin/uk/gov/govuk/data/auth/AuthRepoTest.kt, feature/settings/src/test/kotlin/uk/gov/govuk/settings/SignOutViewModelTest.kt
Revoke refresh token on signout
- [GOVUKAPP-1669](https://govukverify.atlassian.net/browse/GOVUKAPP-1669)
[GOVUKAPP-1669]: https://govukverify.atlassian.net/browse/GOVUKAPP-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1669: Signout revoke token

feature/local/build.gradle.kts, feature/local/src/main/kotlin/uk/govuk/app/local/LocalViewModel.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/remote/LocalApi.kt, feature/local/src/main/kotlin/uk/govuk/app/local/data/remote/model/Address.kt
- [GOVUKAPP-1368](https://govukverify.atlassian.net/browse/GOVUKAPP-1368)
[GOVUKAPP-1368]: https://govukverify.atlassian.net/browse/GOVUKAPP-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1368 : Switch local feature to use the production API

app/src/main/kotlin/uk/gov/govuk/AppUiState.kt, app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt, app/src/main/kotlin/uk/gov/govuk/MainActivity.kt, app/src/main/kotlin/uk/gov/govuk/TimeoutManager.kt, app/src/main/kotlin/uk/gov/govuk/navigation/AppLaunchNavigation.kt, app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt, app/src/test/kotlin/uk/gov/govuk/AppViewModelTest.kt, app/src/test/kotlin/uk/gov/govuk/TimeoutManagerTest.kt, app/src/test/kotlin/uk/gov/govuk/navigation/AppLaunchNavigationTest.kt, config/src/main/kotlin/uk/gov/govuk/config/data/flags/FlagRepo.kt, data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt, data/src/test/kotlin/uk/gov/govuk/data/auth/AuthRepoTest.kt, feature/topics/src/main/kotlin/uk/gov/govuk/topics/DefaultTopicsFeature.kt, feature/topics/src/main/kotlin/uk/gov/govuk/topics/TopicsFeature.kt, feature/topics/src/main/kotlin/uk/gov/govuk/topics/data/TopicsRepo.kt, feature/topics/src/test/kotlin/uk/gov/govuk/topics/data/TopicsRepoTest.kt
Inactivity time out
- [GOVUKAPP-1683](https://govukverify.atlassian.net/browse/GOVUKAPP-1683)
[GOVUKAPP-1683]: https://govukverify.atlassian.net/browse/GOVUKAPP-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1683: Inactivity time out

feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalAddressSelectScreen.kt, feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalAuthoritySelectScreen.kt, feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalConfirmationScreen.kt, feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalExplainerScreen.kt, feature/local/src/main/kotlin/uk/govuk/app/local/ui/LocalLookupScreen.kt
Add heading semantic to Local screens headings
- [GOVUKAPP-1914](https://govukverify.atlassian.net/browse/GOVUKAPP-1914)
https://github.com/user-attachments/assets/41f00e77-b29f-49e0-bae9-3930e661d199
[GOVUKAPP-1914]: https://govukverify.atlassian.net/browse/GOVUKAPP-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1914 Form element roles - Local

config/build.gradle.kts, config/src/main/kotlin/uk/gov/govuk/config/data/flags/DebugFlags.kt, config/src/main/kotlin/uk/gov/govuk/config/data/flags/FlagRepo.kt, config/src/test/kotlin/uk/gov/govuk/config/data/flags/FlagRepoTest.kt
=> Enable login in debug builds

feature/topics/src/main/kotlin/uk/gov/govuk/topics/ui/TopicScreen.kt
When landing on a topic screen set the focus on the topic title
- [GOVUKAPP-1908](https://govukverify.atlassian.net/browse/GOVUKAPP-1908)
https://github.com/user-attachments/assets/755630a9-f3b0-4307-b699-349fbd7d7616
[GOVUKAPP-1908]: https://govukverify.atlassian.net/browse/GOVUKAPP-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1908 Focus order (Topics)

feature/search/src/main/kotlin/uk/gov/govuk/search/ui/component/TextField.kt, feature/search/src/main/res/values/strings.xml
Add content description to search entry textfield
- [GOVUKAPP-1909](https://govukverify.atlassian.net/browse/GOVUKAPP-1909)
https://github.com/user-attachments/assets/5aedcd4d-1e81-449d-8414-eeb4ce0528bc
[GOVUKAPP-1909]: https://govukverify.atlassian.net/browse/GOVUKAPP-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1909 Unlabelled form controls - Home

app/build.gradle.kts, app/src/main/AndroidManifest.xml, data/src/main/AndroidManifest.xml
Add oauth redirect activity to manifest, remove manifest placeholder
=> Deeplink intent fix

data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt, data/src/test/kotlin/uk/gov/govuk/data/auth/AuthRepoTest.kt
Check token response for blank tokens
=> Blank token fix

feature/search/src/main/kotlin/uk/gov/govuk/search/ui/component/TextField.kt
Set cursor colour
- [GOVUKAPP-1883](https://govukverify.atlassian.net/browse/GOVUKAPP-1883)
[GOVUKAPP-1883]: https://govukverify.atlassian.net/browse/GOVUKAPP-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1883: Cursor colour

app/src/main/res/values-v35/styles.xml, app/src/main/res/values/styles.xml
Opt out of edge 2 edge
- [GOVUKAPP-1884](https://govukverify.atlassian.net/browse/GOVUKAPP-1884)
|![Screenshot_20250624_133241](https://github.com/user-attachments/assets/57368f94-8ee8-4759-a506-cef8b1225d0a)|![Screenshot_20250624_132940](https://github.com/user-attachments/assets/c5fb768e-13e9-47a8-aa11-0791d45b40bd)|
[GOVUKAPP-1884]: https://govukverify.atlassian.net/browse/GOVUKAPP-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1884: Open source licenses bug

feature/search/src/main/kotlin/uk/gov/govuk/search/di/SearchModule.kt
Send custom user agent for search and autocomplete
- [GOVUKAPP-1869](https://govukverify.atlassian.net/browse/GOVUKAPP-1869)
[GOVUKAPP-1869]: https://govukverify.atlassian.net/browse/GOVUKAPP-1869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-1869: Search user agent

.github/workflows/pull_request.yml, app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt, app/src/main/kotlin/uk/gov/govuk/login/BiometricSettingsViewModel.kt, app/src/main/kotlin/uk/gov/govuk/navigation/AppLaunchNavigation.kt, app/src/main/res/values/strings.xml, app/src/test/kotlin/uk/gov/govuk/AppViewModelTest.kt, app/src/test/kotlin/uk/gov/govuk/login/BiometricSettingsViewModelTest.kt, app/src/test/kotlin/uk/gov/govuk/navigation/AppLaunchNavigationTest.kt, data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt, data/src/test/kotlin/uk/gov/govuk/data/auth/AuthRepoTest.kt, feature/settings/src/main/kotlin/uk/gov/govuk/settings/SignOutViewModel.kt, feature/settings/src/test/kotlin/uk/gov/govuk/settings/SignOutViewModelTest.kt
=> Biometrics nav fix

data/build.gradle.kts
=> Update auth urls

analytics/src/main/kotlin/uk/gov/govuk/analytics/AnalyticsClient.kt, analytics/src/main/kotlin/uk/gov/govuk/analytics/FirebaseAnalyticsClient.kt, analytics/src/test/kotlin/uk/gov/govuk/analytics/AnalyticsClientTest.kt, analytics/src/test/kotlin/uk/gov/govuk/analytics/FirebaseAnalyticsClientTest.kt, app/build.gradle.kts, data/build.gradle.kts, data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt, data/src/test/kotlin/uk/gov/govuk/data/auth/AuthRepoTest.kt
=> Bump version, fix for blank refresh token

.github/workflows/pull_request.yml, analytics/src/main/kotlin/uk/gov/govuk/analytics/AnalyticsClient.kt, analytics/src/main/kotlin/uk/gov/govuk/analytics/FirebaseAnalyticsClient.kt, analytics/src/test/kotlin/uk/gov/govuk/analytics/AnalyticsClientTest.kt, analytics/src/test/kotlin/uk/gov/govuk/analytics/FirebaseAnalyticsClientTest.kt, app/build.gradle.kts, app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt, app/src/main/kotlin/uk/gov/govuk/login/BiometricSettingsViewModel.kt, app/src/main/kotlin/uk/gov/govuk/navigation/AppLaunchNavigation.kt, app/src/test/kotlin/uk/gov/govuk/AppViewModelTest.kt, app/src/test/kotlin/uk/gov/govuk/login/BiometricSettingsViewModelTest.kt, app/src/test/kotlin/uk/gov/govuk/navigation/AppLaunchNavigationTest.kt, data/build.gradle.kts, data/src/main/kotlin/uk/gov/govuk/data/auth/AuthRepo.kt, data/src/test/kotlin/uk/gov/govuk/data/auth/AuthRepoTest.kt, feature/search/src/main/kotlin/uk/gov/govuk/search/di/SearchModule.kt, feature/settings/src/main/kotlin/uk/gov/govuk/settings/SignOutViewModel.kt, feature/settings/src/test/kotlin/uk/gov/govuk/settings/SignOutViewModelTest.kt
=> Blank refresh token fix

design/src/main/kotlin/uk/gov/govuk/design/ui/theme/Color.kt, feature/chat/build.gradle.kts, feature/chat/src/main/kotlin/uk/gov/govuk/chat/navigation/ChatNavigation.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt, feature/chat/src/main/res/drawable/outline_arrow_upward_24.xml, feature/chat/src/main/res/values/strings.xml
- [GOVUKAPP-2037](https://govukverify.atlassian.net/browse/GOVUKAPP-2037)
- [Figma board](https://www.figma.com/design/rKYEySuNc8aikJWYfEz1wR/2025-04-GOV.UK-Chat-and-AI?node-id=4930-48292&t=Ahi9YzgHLJ306PTh-0)
|---|---|
| <img width="1198" height="2531" alt="light-mode" src="https://github.com/user-attachments/assets/5a848932-9eff-44dc-a4c4-0795d8d6a6b8" /> | <img width="1198" height="2531" alt="dark-mode" src="https://github.com/user-attachments/assets/88b6b2f0-3490-439b-9443-fe9c5864177b" /> |
| <img width="1198" height="2531" alt="light-mode-input" src="https://github.com/user-attachments/assets/bf336095-c79e-4310-9b2c-b1dd85e6acc1" /> | <img width="1198" height="2531" alt="dark-mode-input" src="https://github.com/user-attachments/assets/51d671ee-3b97-4729-bff …
=> GOVUKAPP-2037 : Chat window

.github/workflows/pull_request.yml, app/build.gradle.kts
- Update the version number to 1.0.4 as requested on Jira ticket.
- Update PR workflow to run CI jobs on PR's pointing to feature branches.
- [GOVUKAPP-2158](https://govukverify.atlassian.net/browse/GOVUKAPP-2158)
[GOVUKAPP-2158]: https://govukverify.atlassian.net/browse/GOVUKAPP-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2158 Update version number

app/build.gradle.kts
=> Update the app version name to 1.0.5

design/src/main/kotlin/uk/gov/govuk/design/ui/theme/Color.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ChatViewModel.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt, feature/chat/src/main/res/drawable/baseline_info_24.xml, feature/chat/src/main/res/drawable/outline_arrow_drop_up_24.xml, feature/chat/src/main/res/drawable/outline_chevron_right_24.xml, feature/chat/src/main/res/values/strings.xml, feature/chat/src/test/kotlin/uk/gov/govuk/chat/ChatViewModelTest.kt
- [GOVUKAPP-2039](https://govukverify.atlassian.net/browse/GOVUKAPP-2039)
- [Figma board](https://www.figma.com/design/rKYEySuNc8aikJWYfEz1wR/2025-04-GOV.UK-Chat-and-AI?node-id=3215-2&p=f&t=QniMIT1XMyCZplEF-0)
| <img width="1080" height="2424" alt="light-user" src="https://github.com/user-attachments/assets/ee02c8a1-be67-4026-b0de-70662b7d5337" /> | <img width="1080" height="2424" alt="dark-user" src="https://github.com/user-attachments/assets/fc741d75-ccb5-4897-b8c5-5f5b2d716492" /> |
| <img width="1080" height="2424" alt="light-closed" src="https://github.com/user-attachments/assets/4c83c9f9-1fb1-4db6-8770-32eeec98b124" /> | <img width="1080" height="2424" alt="dark-closed" src="https://github.com/user-attachments/assets/6b3895a4-1f66-41cf-889b-9581e …
=> GOVUKAPP-2039 : Chat messages

feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt, feature/chat/src/main/res/values/strings.xml
Fixes the following issues:
- When PII is detected the submit button should be disabled
- Add alt text for action menu button: 'More options'
- Add alt text for 'submit' button: 'Send message'
- Change focus order so that the text input box is focused on before the action menu button for Talkback
- [GOVUKAPP-2041](https://govukverify.atlassian.net/browse/GOVUKAPP-2041)
[GOVUKAPP-2041]: https://govukverify.atlassian.net/browse/GOVUKAPP-2041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2041 : Post Amigo fixups

feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt
- [GOVUKAPP-2045](https://govukverify.atlassian.net/browse/GOVUKAPP-2045)
- [Figma board](https://www.figma.com/design/rKYEySuNc8aikJWYfEz1wR/2025-04-GOV.UK-Chat-and-AI?node-id=4471-64155&t=84LDEnYSmjUxPCni-0)
| Light | Dark |
| <img width="1080" height="2424" alt="light" src="https://github.com/user-attachments/assets/54f4b9e0-8915-4167-aa66-3056c6a032ce" /> | <img width="1080" height="2424" alt="dark" src="https://github.com/user-attachments/assets/8ff23140-9a0b-416e-b4f6-b98b76997b2a" /> |
[GOVUKAPP-2045]: https://govukverify.atlassian.net/browse/GOVUKAPP-2045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2045 : Clear chat

config/src/main/kotlin/uk/gov/govuk/config/data/flags/FlagRepo.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ChatViewModel.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt
- Introduce lazy list
- Improve auto scrolling
=> Chat screen improvements

app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt, app/src/test/kotlin/uk/gov/govuk/AppViewModelTest.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ChatFeature.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/DefaultChatFeature.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/di/ChatModule.kt, feature/chat/src/test/kotlin/uk/gov/govuk/chat/DefaultChatFeatureTest.kt
Clear conversation on new user login
=> Clear conversation on new user login

config/consumer-rules.pro
Keep new config classes
- [GOVUKAPP-2378](https://govukverify.atlassian.net/browse/GOVUKAPP-2378)
- [Figma board](https://govukverify.atlassian.net/browse/GOVUKAPP-2376)
[GOVUKAPP-2378]: https://govukverify.atlassian.net/browse/GOVUKAPP-2378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2378 Emergency alerts card keep new config classes

app/build.gradle.kts
=> Update version name to 1.0.6

feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/chat/ActionMenu.kt
Disable clear chat when loading
- [GOVUKAPP-2421](https://govukverify.atlassian.net/browse/GOVUKAPP-2421)
[GOVUKAPP-2421]: https://govukverify.atlassian.net/browse/GOVUKAPP-2421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2421 - Disable clear chat

app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/navigation/ChatNavigation.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatOptInScreen.kt
Fix padding and button spacing
- [GOVUKAPP-2277](https://govukverify.atlassian.net/browse/GOVUKAPP-2277)
- [Figma board](https://www.figma.com/design/rKYEySuNc8aikJWYfEz1wR/2025-04-GOV.UK-Chat?node-id=8391-87942&t=0M9Lmlz9yKmV3p56-4)
[GOVUKAPP-2277]: https://govukverify.atlassian.net/browse/GOVUKAPP-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2277: Chat opt in

feature/local/src/main/res/values/strings.xml
Update postcode entry screen content to current requirements
- [GOVUKAPP-2403](https://govukverify.atlassian.net/browse/GOVUKAPP-2403)
- [Figma board](https://www.figma.com/design/N4v2GPQhwZ7DwhqucyJqlu/GOV.UK-apps-and-notifications?node-id=21359-12327&t=4Cz1KmjaAq6cd8rI-4)
| <img width="1344" height="2992" alt="Screenshot_1757407007" src="https://github.com/user-attachments/assets/c6a3edb1-4d28-46f2-a861-6b35c1d9ada9" /> | <img width="1344" height="2992" alt="Screenshot_1757406643" src="https://github.com/user-attachments/assets/9510192f-fcb7-4084-b9d0-3cfb69fd2509" /> |
[GOVUKAPP-2403]: https://govukverify.atlassian.net/browse/GOVUKAPP-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2404 Postcode entry content change

analytics/src/main/kotlin/uk/gov/govuk/analytics/AnalyticsClient.kt, analytics/src/test/kotlin/uk/gov/govuk/analytics/AnalyticsClientTest.kt, app/src/main/kotlin/uk/gov/govuk/AppUiState.kt, app/src/main/kotlin/uk/gov/govuk/AppViewModel.kt, app/src/main/kotlin/uk/gov/govuk/ui/GovUkApp.kt, feature/home/src/main/kotlin/uk/gov/govuk/home/HomeViewModel.kt, feature/home/src/main/kotlin/uk/gov/govuk/home/navigation/HomeNavigation.kt, feature/home/src/main/kotlin/uk/gov/govuk/home/ui/HomeScreen.kt, feature/home/src/test/kotlin/uk/gov/govuk/home/HomeViewModelTest.kt
- [GOVUKAPP-2530](https://govukverify.atlassian.net/browse/GOVUKAPP-2530)
```shell
Logging event: 
origin=app,
name=screen_view(_vs),
params=Bundle[{
language=en, 
screen_title=Homepage, 
ga_event_origin(_o)=app, 
ga_screen_class(_sc)=HomeScreen, 
ga_screen_id(_si)=-4930994503275970786, 
ga_screen(_sn)=Homepage, 
manual_tracking(_mst)=1
}]
```
```shell
Logging event: 
origin=app,
name=screen_view(_vs),
params=Bundle[{
language=en, 
screen_title=Homepage, 
ga_event_origin(_o)=app, 
engagement_time_msec(_et)=56146, 
ga_previous_class(_pc)=ChatOptIn, 
ga_previous_id(_pi)=8802572394675656584, 
ga_previous_screen(_pn)=Chat Opt In Screen, 
ga_screen_class(_sc)=HomeScreen, 
ga_screen_id(_si)=8802572394675656585, 
ga_screen(_sn)=Homepage, 
manual_tracking(_mst)=1, 
type=chatOptOut
}]
Logging …
```
=> GOVUKAPP-2530 : Chat session start stat

feature/chat/build.gradle.kts, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/ActionMenu.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/ChatInput.kt, feature/chat/src/main/res/values/strings.xml, gradle/libs.versions.toml
- [GOVUKAPP-2486](https://govukverify.atlassian.net/browse/GOVUKAPP-2486)
- [Figma board](https://www.figma.com/design/rKYEySuNc8aikJWYfEz1wR/2025-04-GOV.UK-Chat?node-id=9253-25501&t=mKoEpCxXrx4qaDKv-4)
[GOVUKAPP-2486]: https://govukverify.atlassian.net/browse/GOVUKAPP-2486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2486 : Text input field amendments

feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/ActionMenu.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/ChatInput.kt
- [GOVUKAPP-2486](https://govukverify.atlassian.net/browse/GOVUKAPP-2486)
- [Figma board](https://www.figma.com/design/rKYEySuNc8aikJWYfEz1wR/2025-04-GOV.UK-Chat?node-id=9253-25501&t=mKoEpCxXrx4qaDKv-4)
| --- | --- |
| <img width="1398" height="388" alt="vertical-alignment" src="https://github.com/user-attachments/assets/27954e3c-2f54-441d-9c12-d98ddf9277c8" /> | <img width="519" height="71" alt="center-fix" src="https://github.com/user-attachments/assets/fe270f18-7c5b-4913-88b7-ac75bf923eb8" /> |
| <img width="224" height="184" alt="positioning" src="https://github.com/user-attachments/assets/68531dd4-7d4e-4da1-af31-f3e3ed7cb0ca" /> | <img width="300" height="243" alt="Screenshot_20250923_130446" src="https://github.com/user-attachments/assets/3eb117c3-7036-4ad4-965d-2e …
=> GOVUKAPP-2486 : UI tweaks

design/src/main/kotlin/uk/gov/govuk/design/ui/theme/Color.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/ChatScreen.kt, feature/chat/src/main/kotlin/uk/gov/govuk/chat/ui/component/ChatEntry.kt
Tweak chat animations
- [GOVUKAPP-2365](https://govukverify.atlassian.net/browse/GOVUKAPP-2365)
[Screen_recording_20250924_110443.webm](https://github.com/user-attachments/assets/60a55728-1a1c-4cfd-b3f1-fa65b086e685)
[GOVUKAPP-2365]: https://govukverify.atlassian.net/browse/GOVUKAPP-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2365: Chat animations

app/src/main/kotlin/uk/gov/govuk/login/ui/LoginScreen.kt, app/src/main/res/values/strings.xml, design/src/main/kotlin/uk/gov/govuk/design/ui/component/Screen.kt
Add accessibility text to loading spinner
- [GOVUKAPP-2541](https://govukverify.atlassian.net/browse/GOVUKAPP-2541)
[GOVUKAPP-2541]: https://govukverify.atlassian.net/browse/GOVUKAPP-2541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2541: Sign in loading state

design/src/main/kotlin/uk/gov/govuk/design/ui/component/Button.kt, design/src/main/kotlin/uk/gov/govuk/design/ui/theme/Color.kt
Update app buttons to current requirements
- [GOVUKAPP-2578](https://govukverify.atlassian.net/browse/GOVUKAPP-2578)
- [Figma board](https://www.figma.com/design/x5i4a5RT0xMhJAcjoIxefb/2025-06-GOV.UK-app-library-v2--UX-refresh?node-id=577-2713&t=rmi9rCUi74YzC9wI-0)
| <img width="1344" height="2992" alt="Screenshot_1759161671" src="https://github.com/user-attachments/assets/bd89c88d-3990-460f-8ef8-4852a5987b5c" /> | <img width="1344" height="2992" alt="Screenshot_1759161588" src="https://github.com/user-attachments/assets/2810f07c-8715-4169-badb-f93242b24c2f" /> |
[GOVUKAPP-2578]: https://govukverify.atlassian.net/browse/GOVUKAPP-2578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOVUKAPP-2578 Update buttons
